# Trip Extraction — Day-by-Day DuckDB

Processes one day at a time to keep memory footprint small and constant.
Skips dates that already have parquet output (resumable).

## Trip logic
- Poll interval: ~450 seconds
- **Cell handover** (cell_id changes between consecutive polls) = vehicle moving
- **Stationary** = same cell for >= `STATIONARY_POLLS` consecutive polls
- **Trip** = continuous run of handovers between two stationary periods

```
polls:  [C1] [C2] [C3] [C3] [C3] [C4] [C5] [C5] [C5]
        move move move same same move move same same
        |------ TRIP 1 ------|  park  |--- TRIP 2 ---|
```

In [1]:
## Config

import duckdb
import os
from pathlib import Path

HANDOVER_GLOB = "/home/jovyan/data/stage/handover_events/**/*.parquet"
STAGE_DIR = Path("/home/jovyan/data/stage/trips")
TMP_DIR   = "/tmp/duckdb_tmp"

# How many consecutive same-cell polls = stationary
STATIONARY_POLLS = 3      # 3 x 450s = ~22 min

# Minimum cell handovers for a trip to be kept
MIN_HANDOVERS = 4

# Minimum distinct cells visited — filters cell-edge oscillation
MIN_CELLS = 10

MAX_FILES = 30

STAGE_DIR.mkdir(parents=True, exist_ok=True)
os.makedirs(TMP_DIR, exist_ok=True)

print(f"HANDOVER_GLOB={HANDOVER_GLOB}")
print(f"TMP_DIR={TMP_DIR}")
print(f"STATIONARY_POLLS={STATIONARY_POLLS}, MIN_HANDOVERS={MIN_HANDOVERS}, MIN_CELLS={MIN_CELLS}")

HANDOVER_GLOB=/home/jovyan/data/stage/handover_events/**/*.parquet
TMP_DIR=/tmp/duckdb_tmp
STATIONARY_POLLS=3, MIN_HANDOVERS=4, MIN_CELLS=10

In [2]:
## Connect and configure DuckDB

try:
    existing_con = globals().get("con")
    if existing_con is not None:
        existing_con.close()
except (Exception, NameError):
    pass

con = duckdb.connect()
con.execute(f"SET temp_directory='{TMP_DIR}'")
con.execute("SET memory_limit='16GB'")
con.execute("SET preserve_insertion_order=false")
con.execute("SET threads=4")
con.execute("SET enable_progress_bar=false")
con.execute(f"CREATE OR REPLACE VIEW handover_events AS SELECT * FROM read_parquet('{HANDOVER_GLOB}')")

summary = con.execute("""
    SELECT
        COUNT(*)        AS total_rows,
        MIN(event_date) AS first_date,
        MAX(event_date) AS last_date,
        COUNT(DISTINCT event_date) AS n_dates
    FROM handover_events
""").df()
print(summary.to_string(index=False))

 total_rows first_date  last_date  n_dates
 1735661691 2025-01-01 2025-12-31      364

In [3]:
## Get list of dates to process

dates = [
    row[0] for row in
    con.execute("SELECT DISTINCT event_date FROM handover_events ORDER BY event_date").fetchall()
]

print(f"Dates to process: {len(dates)}")
print(f"  First: {dates[0]}")
print(f"  Last:  {dates[-1]}")

Dates to process: 364
  First: 2025-01-01
  Last:  2025-12-31

In [4]:
## Process one day at a time

import time

total_trips = 0
skipped = 0
run_start = time.time()

for i, event_date in enumerate(dates, 1):

    # --- Resumable: skip if parquet already written for this date ---
    out_dir = STAGE_DIR / f"event_date={event_date}"
    if out_dir.exists() and any(out_dir.glob("*.parquet")):
        skipped += 1
        print(f"[{i}/{len(dates)}] SKIP {event_date} (already done)")
        continue

    day_start = time.time()

    # --- Step A: build trips_raw for this date only ---
    con.execute("DROP TABLE IF EXISTS trips_raw")
    con.execute(f"""
    CREATE TABLE trips_raw AS
    WITH
    ranked AS (
        SELECT
            vehicle_id, imsi, event_ts, cell_id, rat, event_date,
            LAG(cell_id) OVER (PARTITION BY vehicle_id ORDER BY event_ts) AS prev_cell,
            CASE
                WHEN cell_id != LAG(cell_id) OVER (PARTITION BY vehicle_id ORDER BY event_ts)
                  OR LAG(cell_id) OVER (PARTITION BY vehicle_id ORDER BY event_ts) IS NULL
                THEN 1 ELSE 0
            END AS cell_changed
        FROM handover_events
        WHERE event_date = '{event_date}'
    ),
    with_run AS (
        SELECT *,
            SUM(cell_changed) OVER (PARTITION BY vehicle_id ORDER BY event_ts) AS cell_run_id
        FROM ranked
    ),
    with_poll_count AS (
        SELECT *,
            ROW_NUMBER() OVER (PARTITION BY vehicle_id, cell_run_id ORDER BY event_ts) AS same_cell_poll_count
        FROM with_run
    ),
    with_stationary AS (
        SELECT *,
            same_cell_poll_count >= {STATIONARY_POLLS} AS stationary,
            LAG(same_cell_poll_count >= {STATIONARY_POLLS})
                OVER (PARTITION BY vehicle_id ORDER BY event_ts) AS prev_stationary
        FROM with_poll_count
    ),
    with_trip_flags AS (
        SELECT *,
            CASE
                WHEN cell_changed = 1
                 AND (prev_stationary OR prev_stationary IS NULL)
                THEN 1 ELSE 0
            END AS trip_start_flag
        FROM with_stationary
    ),
    with_trip_seq AS (
        SELECT *,
            SUM(trip_start_flag) OVER (PARTITION BY vehicle_id ORDER BY event_ts) AS trip_seq,
            NOT stationary AS in_trip
        FROM with_trip_flags
    )
    SELECT *,
        CASE WHEN NOT stationary
            THEN vehicle_id || '_trip_' || LPAD(CAST(trip_seq AS VARCHAR), 3, '0')
            ELSE NULL
        END AS trip_id
    FROM with_trip_seq
    """)

    # --- Step B: aggregate trip summaries ---
    con.execute("DROP TABLE IF EXISTS trip_agg")
    con.execute("""
    CREATE TABLE trip_agg AS
    SELECT
        vehicle_id, imsi, trip_id, trip_seq, event_date,
        MIN(event_ts)                                      AS trip_start,
        MAX(event_ts)                                      AS trip_end,
        COUNT(*)                                           AS n_events,
        COUNT(DISTINCT cell_id)                            AS n_cells,
        SUM(CASE WHEN cell_changed = 1 THEN 1 ELSE 0 END) AS n_handovers,
        FIRST(cell_id ORDER BY event_ts)                   AS first_cell,
        LAST(cell_id ORDER BY event_ts)                    AS last_cell,
        MODE(rat)                                          AS dominant_rat
    FROM trips_raw
    WHERE in_trip
    GROUP BY vehicle_id, imsi, trip_id, trip_seq, event_date
    """)

    # --- Step C: free trips_raw, build cell sequences ---
    con.execute("DROP TABLE IF EXISTS trips_raw")

    con.execute("DROP TABLE IF EXISTS cell_sequences")
    con.execute(f"""
    CREATE TABLE cell_sequences AS
    SELECT
        h.vehicle_id || '_trip_' || LPAD(CAST(t.trip_seq AS VARCHAR), 3, '0') AS trip_id,
        STRING_AGG(h.cell_id, ' -> ' ORDER BY h.event_ts) AS cell_sequence
    FROM handover_events h
    JOIN trip_agg t
        ON  h.vehicle_id = t.vehicle_id
        AND h.event_ts  >= t.trip_start
        AND h.event_ts  <= t.trip_end
    WHERE h.event_date = '{event_date}'
    GROUP BY 1
    """)

    # --- Step D: join and apply filters, write parquet ---
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / "trips.parquet"

    n_trips = con.execute(f"""
    COPY (
        SELECT
            a.vehicle_id, a.imsi, a.event_date, a.trip_id, a.trip_seq,
            a.trip_start, a.trip_end,
            ROUND(DATEDIFF('second', a.trip_start, a.trip_end) / 60.0, 1) AS duration_minutes,
            a.n_handovers, a.n_cells, a.n_events,
            a.first_cell, a.last_cell, a.dominant_rat,
            s.cell_sequence
        FROM trip_agg a
        LEFT JOIN cell_sequences s ON a.trip_id = s.trip_id
        WHERE a.trip_id    IS NOT NULL
          AND a.n_handovers >= {MIN_HANDOVERS}
          AND a.n_cells     >= {MIN_CELLS}
        ORDER BY vehicle_id, trip_start
    ) TO '{out_file}' (FORMAT PARQUET)
    """).fetchone()[0]

    # --- Cleanup working tables ---
    con.execute("DROP TABLE IF EXISTS trip_agg")
    con.execute("DROP TABLE IF EXISTS cell_sequences")

    total_trips += n_trips
    elapsed = time.time() - day_start
    print(f"[{i}/{len(dates)}] {event_date} → {n_trips:,} trips ({elapsed:.1f}s)")

total_elapsed = time.time() - run_start
print(f"\nDone. {len(dates) - skipped} days processed, {skipped} skipped.")
print(f"Total trips written: {total_trips:,}")
print(f"Total runtime: {total_elapsed/60:.1f} min")

[1/364] 2025-01-01 → 0 trips (8.9s)
[2/364] 2025-01-02 → 0 trips (8.2s)
[3/364] 2025-01-03 → 0 trips (10.2s)
[4/364] 2025-01-04 → 1 trips (15.5s)
[5/364] 2025-01-05 → 0 trips (11.4s)
[6/364] 2025-01-06 → 0 trips (10.3s)
[7/364] 2025-01-07 → 1 trips (11.3s)
[8/364] 2025-01-08 → 0 trips (15.5s)
[9/364] 2025-01-09 → 0 trips (52.8s)
[10/364] 2025-01-10 → 0 trips (9.6s)
[11/364] 2025-01-11 → 0 trips (9.4s)
[12/364] 2025-01-12 → 0 trips (9.0s)
[13/364] 2025-01-13 → 1 trips (8.6s)
[14/364] 2025-01-14 → 0 trips (8.4s)
[15/364] 2025-01-15 → 0 trips (8.9s)
[16/364] 2025-01-17 → 3 trips (8.8s)
[17/364] 2025-01-18 → 3 trips (7.6s)
[18/364] 2025-01-19 → 3 trips (8.1s)
[19/364] 2025-01-20 → 7 trips (8.1s)
[20/364] 2025-01-21 → 4 trips (8.0s)
[21/364] 2025-01-22 → 14 trips (7.7s)
[22/364] 2025-01-23 → 10 trips (7.9s)
[23/364] 2025-01-24 → 5 trips (8.1s)
[24/364] 2025-01-25 → 3 trips (7.9s)
[25/364] 2025-01-26 → 4 trips (8.0s)
[26/364] 2025-01-27 → 14 trips (8.0s)
[27/364] 2025-01-28 → 9 trips (7.9s)
[28/364] 2025-01-29 → 2 trips (7.6s)
[29/364] 2025-01-30 → 8 trips (7.9s)
[30/364] 2025-01-31 → 7 trips (7.7s)
[31/364] 2025-02-01 → 6 trips (8.0s)
[32/364] 2025-02-02 → 5 trips (7.6s)
[33/364] 2025-02-03 → 65 trips (7.8s)
[34/364] 2025-02-04 → 649 trips (8.6s)
[35/364] 2025-02-05 → 1,186 trips (9.2s)
[36/364] 2025-02-06 → 947 trips (9.4s)
[37/364] 2025-02-07 → 1,163 trips (9.9s)
[38/364] 2025-02-08 → 947 trips (9.5s)
[39/364] 2025-02-09 → 751 trips (8.9s)
[40/364] 2025-02-10 → 863 trips (9.0s)
[41/364] 2025-02-11 → 971 trips (9.0s)
[42/364] 2025-02-12 → 867 trips (8.5s)
[43/364] 2025-02-13 → 765 trips (8.8s)
[44/364] 2025-02-14 → 949 trips (8.9s)
[45/364] 2025-02-15 → 740 trips (8.6s)
[46/364] 2025-02-16 → 629 trips (8.5s)
[47/364] 2025-02-17 → 859 trips (8.9s)
[48/364] 2025-02-18 → 953 trips (8.8s)
[49/364] 2025-02-19 → 859 trips (8.6s)
[50/364] 2025-02-20 → 1,011 trips (9.0s)
[51/364] 2025-02-21 → 977 trips (9.8s)
[52/364] 2025-02-22 → 791 trips (8.6s)
[53/364] 2025-02-23 → 741 trips (8.9s)
[54/364] 2025-02-24 → 794 trips (9.2s)
[55/364] 2025-02-25 → 950 trips (8.9s)
[56/364] 2025-02-26 → 921 trips (9.6s)
[57/364] 2025-02-27 → 1,000 trips (9.1s)
[58/364] 2025-02-28 → 934 trips (9.0s)
[59/364] 2025-03-01 → 863 trips (8.6s)
[60/364] 2025-03-02 → 789 trips (9.1s)
[61/364] 2025-03-03 → 724 trips (8.9s)
[62/364] 2025-03-04 → 1,656 trips (8.8s)
[63/364] 2025-03-05 → 3,282 trips (11.0s)
[64/364] 2025-03-06 → 3,555 trips (10.9s)
[65/364] 2025-03-07 → 3,451 trips (10.4s)
[66/364] 2025-03-08 → 2,289 trips (10.6s)
[67/364] 2025-03-09 → 1,800 trips (10.7s)
[68/364] 2025-03-10 → 3,268 trips (10.3s)
[69/364] 2025-03-11 → 3,654 trips (10.8s)
[70/364] 2025-03-12 → 3,709 trips (10.6s)
[71/364] 2025-03-13 → 3,660 trips (10.6s)
[72/364] 2025-03-14 → 3,552 trips (11.1s)
[73/364] 2025-03-15 → 2,122 trips (10.4s)
[74/364] 2025-03-16 → 1,815 trips (10.4s)
[75/364] 2025-03-17 → 3,364 trips (10.9s)
[76/364] 2025-03-18 → 3,681 trips (10.8s)
[77/364] 2025-03-19 → 3,768 trips (10.6s)
[78/364] 2025-03-20 → 3,705 trips (11.1s)
[79/364] 2025-03-21 → 3,718 trips (10.5s)
[80/364] 2025-03-22 → 2,250 trips (10.8s)
[81/364] 2025-03-23 → 1,756 trips (10.7s)
[82/364] 2025-03-24 → 3,198 trips (10.5s)
[83/364] 2025-03-25 → 3,713 trips (11.1s)
[84/364] 2025-03-26 → 3,741 trips (10.8s)
[85/364] 2025-03-27 → 3,705 trips (10.6s)
[86/364] 2025-03-28 → 3,590 trips (10.6s)
[87/364] 2025-03-29 → 2,276 trips (10.1s)
[88/364] 2025-03-30 → 1,734 trips (10.2s)
[89/364] 2025-03-31 → 3,277 trips (10.5s)
[90/364] 2025-04-01 → 3,615 trips (10.2s)
[91/364] 2025-04-02 → 3,684 trips (10.5s)
[92/364] 2025-04-03 → 3,766 trips (10.4s)
[93/364] 2025-04-04 → 3,871 trips (11.3s)
[94/364] 2025-04-05 → 2,625 trips (11.7s)
[95/364] 2025-04-06 → 2,138 trips (11.5s)
[96/364] 2025-04-07 → 3,656 trips (11.1s)
[97/364] 2025-04-08 → 4,199 trips (11.6s)
[98/364] 2025-04-09 → 4,293 trips (11.4s)
[99/364] 2025-04-10 → 4,354 trips (11.1s)
[100/364] 2025-04-11 → 4,092 trips (11.6s)
[101/364] 2025-04-12 → 2,678 trips (11.4s)
[102/364] 2025-04-13 → 2,283 trips (10.9s)
[103/364] 2025-04-14 → 3,918 trips (10.9s)
[104/364] 2025-04-15 → 4,241 trips (11.0s)
[105/364] 2025-04-16 → 4,354 trips (11.3s)
[106/364] 2025-04-17 → 4,559 trips (10.8s)
[107/364] 2025-04-18 → 3,979 trips (11.1s)
[108/364] 2025-04-19 → 2,550 trips (11.0s)
[109/364] 2025-04-20 → 1,882 trips (10.6s)
[110/364] 2025-04-21 → 3,832 trips (11.1s)
[111/364] 2025-04-22 → 4,272 trips (11.1s)
[112/364] 2025-04-23 → 4,194 trips (10.9s)
[113/364] 2025-04-24 → 4,333 trips (11.1s)
[114/364] 2025-04-25 → 4,073 trips (10.7s)
[115/364] 2025-04-26 → 2,810 trips (10.8s)
[116/364] 2025-04-27 → 2,256 trips (10.8s)
[117/364] 2025-04-28 → 3,865 trips (10.6s)
[118/364] 2025-04-29 → 4,204 trips (11.0s)
[119/364] 2025-04-30 → 4,415 trips (11.0s)
[120/364] 2025-05-01 → 4,382 trips (10.6s)
[121/364] 2025-05-02 → 4,253 trips (11.1s)
[122/364] 2025-05-03 → 2,763 trips (10.8s)
[123/364] 2025-05-04 → 2,216 trips (10.7s)
[124/364] 2025-05-05 → 3,840 trips (11.1s)
[125/364] 2025-05-06 → 4,099 trips (10.7s)
[126/364] 2025-05-07 → 4,146 trips (10.9s)
[127/364] 2025-05-08 → 4,407 trips (11.0s)
[128/364] 2025-05-09 → 4,389 trips (10.8s)
[129/364] 2025-05-10 → 2,935 trips (11.1s)
[130/364] 2025-05-11 → 2,272 trips (10.9s)
[131/364] 2025-05-12 → 3,872 trips (10.6s)
[132/364] 2025-05-13 → 4,163 trips (11.1s)
[133/364] 2025-05-14 → 4,265 trips (10.8s)
[134/364] 2025-05-15 → 5,354 trips (11.2s)
[135/364] 2025-05-16 → 6,042 trips (12.6s)
[136/364] 2025-05-17 → 4,500 trips (12.2s)
[137/364] 2025-05-18 → 3,821 trips (12.4s)
[138/364] 2025-05-19 → 5,889 trips (13.1s)
[139/364] 2025-05-20 → 6,408 trips (13.4s)
[140/364] 2025-05-21 → 6,848 trips (14.0s)
[141/364] 2025-05-22 → 7,197 trips (14.5s)
[142/364] 2025-05-23 → 7,239 trips (14.8s)
[143/364] 2025-05-24 → 4,710 trips (14.4s)
[144/364] 2025-05-25 → 3,769 trips (14.6s)
[145/364] 2025-05-26 → 4,134 trips (14.3s)
[146/364] 2025-05-27 → 6,395 trips (14.5s)
[147/364] 2025-05-28 → 6,070 trips (13.2s)
[148/364] 2025-05-29 → 6,275 trips (13.6s)
[149/364] 2025-05-30 → 6,344 trips (13.2s)
[150/364] 2025-05-31 → 4,697 trips (13.7s)
[151/364] 2025-06-01 → 4,177 trips (13.5s)
[152/364] 2025-06-02 → 5,662 trips (13.4s)
[153/364] 2025-06-03 → 5,883 trips (13.1s)
[154/364] 2025-06-04 → 5,975 trips (13.1s)
[155/364] 2025-06-05 → 6,081 trips (13.3s)
[156/364] 2025-06-06 → 5,386 trips (11.9s)
[157/364] 2025-06-07 → 3,491 trips (11.4s)
[158/364] 2025-06-08 → 3,088 trips (11.0s)
[159/364] 2025-06-09 → 4,423 trips (11.4s)
[160/364] 2025-06-10 → 4,659 trips (11.6s)
[161/364] 2025-06-11 → 4,642 trips (11.1s)
[162/364] 2025-06-12 → 4,805 trips (11.4s)
[163/364] 2025-06-13 → 5,002 trips (11.2s)
[164/364] 2025-06-14 → 3,548 trips (11.1s)
[165/364] 2025-06-15 → 3,030 trips (11.2s)
[166/364] 2025-06-16 → 4,572 trips (11.2s)
[167/364] 2025-06-17 → 4,603 trips (11.3s)
[168/364] 2025-06-18 → 4,799 trips (11.3s)
[169/364] 2025-06-19 → 4,889 trips (10.9s)
[170/364] 2025-06-20 → 4,889 trips (11.3s)
[171/364] 2025-06-21 → 3,469 trips (11.2s)
[172/364] 2025-06-22 → 3,034 trips (11.1s)
[173/364] 2025-06-23 → 4,541 trips (11.4s)
[174/364] 2025-06-24 → 4,520 trips (11.0s)
[175/364] 2025-06-25 → 4,654 trips (11.2s)
[176/364] 2025-06-26 → 4,611 trips (11.4s)
[177/364] 2025-06-27 → 4,828 trips (11.0s)
[178/364] 2025-06-28 → 3,413 trips (11.2s)
[179/364] 2025-06-29 → 2,956 trips (11.1s)
[180/364] 2025-06-30 → 4,210 trips (10.8s)
[181/364] 2025-07-01 → 4,345 trips (11.4s)
[182/364] 2025-07-02 → 4,377 trips (11.0s)
[183/364] 2025-07-03 → 4,446 trips (11.3s)
[184/364] 2025-07-04 → 2,112 trips (11.3s)
[185/364] 2025-07-05 → 2,412 trips (10.8s)
[186/364] 2025-07-06 → 2,831 trips (11.1s)
[187/364] 2025-07-07 → 4,155 trips (11.2s)
[188/364] 2025-07-08 → 4,066 trips (11.1s)
[189/364] 2025-07-09 → 4,069 trips (11.3s)
[190/364] 2025-07-10 → 4,293 trips (11.0s)
[191/364] 2025-07-11 → 4,341 trips (11.2s)
[192/364] 2025-07-12 → 3,021 trips (11.1s)
[193/364] 2025-07-13 → 2,844 trips (10.7s)
[194/364] 2025-07-14 → 3,934 trips (11.2s)
[195/364] 2025-07-15 → 3,883 trips (11.3s)
[196/364] 2025-07-16 → 4,044 trips (10.9s)
[197/364] 2025-07-17 → 4,316 trips (11.1s)
[198/364] 2025-07-18 → 4,173 trips (11.2s)
[199/364] 2025-07-19 → 3,017 trips (10.9s)
[200/364] 2025-07-20 → 2,768 trips (11.3s)
[201/364] 2025-07-21 → 3,876 trips (10.8s)
[202/364] 2025-07-22 → 3,899 trips (11.2s)
[203/364] 2025-07-23 → 3,951 trips (11.0s)
[204/364] 2025-07-24 → 4,059 trips (10.6s)
[205/364] 2025-07-25 → 4,230 trips (11.2s)
[206/364] 2025-07-26 → 2,890 trips (11.0s)
[207/364] 2025-07-27 → 2,842 trips (10.9s)
[208/364] 2025-07-28 → 3,741 trips (11.2s)
[209/364] 2025-07-29 → 3,776 trips (10.9s)
[210/364] 2025-07-30 → 3,851 trips (11.0s)
[211/364] 2025-07-31 → 4,171 trips (11.3s)
[212/364] 2025-08-01 → 4,241 trips (11.0s)
[213/364] 2025-08-02 → 2,888 trips (11.0s)
[214/364] 2025-08-03 → 2,563 trips (11.0s)
[215/364] 2025-08-04 → 3,718 trips (10.9s)
[216/364] 2025-08-05 → 3,775 trips (11.0s)
[217/364] 2025-08-06 → 3,881 trips (10.8s)
[218/364] 2025-08-07 → 4,066 trips (10.8s)
[219/364] 2025-08-08 → 4,129 trips (11.0s)
[220/364] 2025-08-09 → 3,020 trips (10.6s)
[221/364] 2025-08-10 → 2,666 trips (10.9s)
[222/364] 2025-08-11 → 3,837 trips (11.2s)
[223/364] 2025-08-12 → 3,890 trips (10.6s)
[224/364] 2025-08-13 → 3,894 trips (10.9s)
[225/364] 2025-08-14 → 4,113 trips (10.8s)
[226/364] 2025-08-15 → 4,210 trips (10.5s)
[227/364] 2025-08-16 → 2,888 trips (11.0s)
[228/364] 2025-08-17 → 2,578 trips (10.8s)
[229/364] 2025-08-18 → 3,814 trips (11.1s)
[230/364] 2025-08-19 → 3,793 trips (11.1s)
[231/364] 2025-08-20 → 3,876 trips (10.9s)
[232/364] 2025-08-21 → 4,178 trips (11.1s)
[233/364] 2025-08-22 → 4,327 trips (11.3s)
[234/364] 2025-08-23 → 2,901 trips (10.6s)
[235/364] 2025-08-24 → 2,481 trips (10.9s)
[236/364] 2025-08-25 → 3,725 trips (10.9s)
[237/364] 2025-08-26 → 3,861 trips (10.6s)
[238/364] 2025-08-27 → 3,966 trips (11.1s)
[239/364] 2025-08-28 → 4,171 trips (11.0s)
[240/364] 2025-08-29 → 4,451 trips (11.0s)
[241/364] 2025-08-30 → 2,744 trips (10.9s)
[242/364] 2025-08-31 → 2,254 trips (10.8s)
[243/364] 2025-09-01 → 2,714 trips (10.9s)
[244/364] 2025-09-02 → 3,897 trips (11.1s)
[245/364] 2025-09-03 → 4,025 trips (10.8s)
[246/364] 2025-09-04 → 3,996 trips (11.1s)
[247/364] 2025-09-05 → 4,126 trips (10.8s)
[248/364] 2025-09-06 → 2,850 trips (10.9s)
[249/364] 2025-09-07 → 2,470 trips (10.9s)
[250/364] 2025-09-08 → 3,769 trips (10.8s)
[251/364] 2025-09-09 → 3,769 trips (11.0s)
[252/364] 2025-09-10 → 3,889 trips (11.0s)
[253/364] 2025-09-11 → 4,096 trips (10.8s)
[254/364] 2025-09-12 → 4,144 trips (11.1s)
[255/364] 2025-09-13 → 2,942 trips (11.0s)
[256/364] 2025-09-14 → 2,447 trips (10.8s)
[257/364] 2025-09-15 → 3,722 trips (11.1s)
[258/364] 2025-09-16 → 3,782 trips (10.8s)
[259/364] 2025-09-17 → 3,892 trips (10.7s)
[260/364] 2025-09-18 → 4,045 trips (11.1s)
[261/364] 2025-09-19 → 4,238 trips (10.9s)
[262/364] 2025-09-20 → 2,969 trips (11.0s)
[263/364] 2025-09-21 → 2,595 trips (11.1s)
[264/364] 2025-09-22 → 3,654 trips (10.8s)
[265/364] 2025-09-23 → 3,760 trips (11.0s)
[266/364] 2025-09-24 → 3,764 trips (11.0s)
[267/364] 2025-09-25 → 4,072 trips (11.0s)
[268/364] 2025-09-26 → 4,203 trips (10.9s)
[269/364] 2025-09-27 → 2,926 trips (11.0s)
[270/364] 2025-09-28 → 2,647 trips (11.0s)
[271/364] 2025-09-29 → 3,832 trips (11.2s)
[272/364] 2025-09-30 → 3,847 trips (10.8s)
[273/364] 2025-10-01 → 3,988 trips (11.1s)
[274/364] 2025-10-02 → 3,881 trips (10.8s)
[275/364] 2025-10-03 → 4,201 trips (11.0s)
[276/364] 2025-10-04 → 2,931 trips (10.8s)
[277/364] 2025-10-05 → 2,629 trips (10.9s)
[278/364] 2025-10-06 → 3,774 trips (11.2s)
[279/364] 2025-10-07 → 3,642 trips (11.4s)
[280/364] 2025-10-08 → 3,750 trips (10.9s)
[281/364] 2025-10-09 → 4,145 trips (11.0s)
[282/364] 2025-10-10 → 4,242 trips (11.1s)
[283/364] 2025-10-11 → 2,928 trips (10.8s)
[284/364] 2025-10-12 → 2,581 trips (10.8s)
[285/364] 2025-10-13 → 3,610 trips (10.8s)
[286/364] 2025-10-14 → 3,728 trips (10.7s)
[287/364] 2025-10-15 → 3,460 trips (10.9s)
[288/364] 2025-10-16 → 2,272 trips (9.6s)
[289/364] 2025-10-17 → 2,988 trips (10.0s)
[290/364] 2025-10-18 → 10,065 trips (20.5s)
[291/364] 2025-10-19 → 10,632 trips (28.4s)
[292/364] 2025-10-20 → 18,258 trips (28.2s)
[293/364] 2025-10-21 → 18,715 trips (28.2s)
[294/364] 2025-10-22 → 19,380 trips (28.0s)
[295/364] 2025-10-23 → 20,199 trips (28.0s)
[296/364] 2025-10-24 → 20,607 trips (28.0s)
[297/364] 2025-10-25 → 13,833 trips (27.8s)
[298/364] 2025-10-26 → 12,132 trips (27.4s)
[299/364] 2025-10-27 → 18,011 trips (28.3s)
[300/364] 2025-10-28 → 18,545 trips (29.3s)
[301/364] 2025-10-29 → 19,057 trips (31.1s)
[302/364] 2025-10-30 → 19,417 trips (33.1s)
[303/364] 2025-10-31 → 19,328 trips (28.2s)
[304/364] 2025-11-01 → 13,397 trips (27.3s)
[305/364] 2025-11-02 → 10,980 trips (27.3s)
[306/364] 2025-11-03 → 17,809 trips (28.0s)
[307/364] 2025-11-04 → 18,085 trips (27.6s)
[308/364] 2025-11-05 → 18,534 trips (27.9s)
[309/364] 2025-11-06 → 19,380 trips (27.9s)
[310/364] 2025-11-07 → 20,369 trips (27.7s)
[311/364] 2025-11-08 → 13,870 trips (27.5s)
[312/364] 2025-11-09 → 11,683 trips (27.4s)
[313/364] 2025-11-10 → 17,402 trips (28.4s)
[314/364] 2025-11-11 → 16,876 trips (28.5s)
[315/364] 2025-11-12 → 18,111 trips (28.1s)
[316/364] 2025-11-13 → 19,113 trips (28.0s)
[317/364] 2025-11-14 → 19,687 trips (27.8s)
[318/364] 2025-11-15 → 13,438 trips (27.6s)
[319/364] 2025-11-16 → 11,354 trips (26.8s)
[320/364] 2025-11-17 → 17,457 trips (28.4s)
[321/364] 2025-11-18 → 17,894 trips (28.2s)
[322/364] 2025-11-19 → 18,292 trips (27.6s)
[323/364] 2025-11-20 → 18,732 trips (27.8s)
[324/364] 2025-11-21 → 19,639 trips (27.9s)
[325/364] 2025-11-22 → 13,894 trips (27.4s)
[326/364] 2025-11-23 → 10,912 trips (27.1s)
[327/364] 2025-11-24 → 17,407 trips (27.5s)
[328/364] 2025-11-25 → 18,471 trips (27.4s)
[329/364] 2025-11-26 → 18,871 trips (27.5s)
[330/364] 2025-11-27 → 8,492 trips (26.4s)
[331/364] 2025-11-28 → 12,998 trips (26.5s)
[332/364] 2025-11-29 → 11,748 trips (27.1s)
[333/364] 2025-11-30 → 11,817 trips (27.0s)
[334/364] 2025-12-01 → 17,812 trips (27.6s)
[335/364] 2025-12-02 → 16,785 trips (27.3s)
[336/364] 2025-12-03 → 18,368 trips (27.6s)
[337/364] 2025-12-04 → 18,628 trips (27.8s)
[338/364] 2025-12-05 → 18,487 trips (27.8s)
[339/364] 2025-12-06 → 12,902 trips (27.2s)
[340/364] 2025-12-07 → 10,390 trips (27.1s)
[341/364] 2025-12-08 → 17,115 trips (27.9s)
[342/364] 2025-12-09 → 17,696 trips (27.4s)
[343/364] 2025-12-10 → 18,069 trips (27.5s)
[344/364] 2025-12-11 → 19,270 trips (28.1s)
[345/364] 2025-12-12 → 19,269 trips (27.7s)
[346/364] 2025-12-13 → 13,694 trips (27.1s)
[347/364] 2025-12-14 → 10,857 trips (26.8s)
[348/364] 2025-12-15 → 17,282 trips (27.4s)
[349/364] 2025-12-16 → 18,057 trips (27.2s)
[350/364] 2025-12-17 → 18,678 trips (27.6s)
[351/364] 2025-12-18 → 19,120 trips (28.1s)
[352/364] 2025-12-19 → 19,717 trips (27.8s)
[353/364] 2025-12-20 → 14,217 trips (27.5s)
[354/364] 2025-12-21 → 10,931 trips (27.4s)
[355/364] 2025-12-22 → 17,850 trips (28.2s)
[356/364] 2025-12-23 → 18,003 trips (28.4s)
[357/364] 2025-12-24 → 12,140 trips (28.6s)
[358/364] 2025-12-25 → 5,333 trips (27.6s)
[359/364] 2025-12-26 → 12,235 trips (27.6s)
[360/364] 2025-12-27 → 11,553 trips (27.7s)
[361/364] 2025-12-28 → 9,856 trips (27.6s)
[362/364] 2025-12-29 → 14,621 trips (28.2s)
[363/364] 2025-12-30 → 15,608 trips (27.9s)
[364/364] 2025-12-31 → 13,758 trips (28.1s)

Done. 364 days processed, 0 skipped.
Total trips written: 2,085,238
Total runtime: 87.0 min

In [5]:
## Register trips table in DuckDB from stage partitions only

TRIPS_STAGE_GLOB = f"{STAGE_DIR}/event_date=*/trips.parquet"
print(f"Loading staged trips from: {TRIPS_STAGE_GLOB}")

con.execute("DROP TABLE IF EXISTS trips")
con.execute(f"""
    CREATE TABLE trips AS
    SELECT *
    FROM read_parquet('{TRIPS_STAGE_GLOB}')
""")

required_cols = {
    "vehicle_id", "imsi", "event_date", "trip_id", "trip_seq",
    "trip_start", "trip_end", "duration_minutes", "n_handovers",
    "n_cells", "n_events", "first_cell", "last_cell", "dominant_rat", "cell_sequence"
}
present_cols = {r[1] for r in con.execute("PRAGMA table_info('trips')").fetchall()}
missing = sorted(required_cols - present_cols)
if missing:
    raise ValueError(f"trips table missing expected columns: {missing}")

con.execute("""
    SELECT
        COUNT(*)                       AS n_trips,
        COUNT(DISTINCT vehicle_id)     AS vehicles,
        SUM(n_handovers)               AS total_handovers,
        ROUND(AVG(duration_minutes),1) AS avg_duration_min,
        MIN(event_date)                AS first_date,
        MAX(event_date)                AS last_date
    FROM trips
""").df()

Loading staged trips from: /home/jovyan/data/stage/trips/event_date=*/trips.parquet

   n_trips  vehicles  total_handovers  avg_duration_min first_date  last_date
0  2085238     93359       36206445.0             159.7 2025-01-04 2025-12-31

In [6]:
## Sanity checks

print("=== Top 10 most-active vehicles ===")
con.execute("""
    SELECT vehicle_id,
           COUNT(*)         AS n_trips,
           SUM(n_handovers) AS total_handovers
    FROM trips
    GROUP BY vehicle_id
    ORDER BY total_handovers DESC
    LIMIT 10
""").df()

=== Top 10 most-active vehicles ===

                         vehicle_id  n_trips  total_handovers
0  0672B8A81103E3A99FA8878E0E81250F      613          12329.0
1  D35EFC990419ADFE51A7427BC53202B6      550          11196.0
2  EFE10DB9261CE8EFD35C9DD16C6C3C81      527          10996.0
3  A1B17FAF6EFAF977AD84EFA0C61304F5      462          10909.0
4  18AE84AD76C67003A516520D6BF49ACC      473          10553.0
5  668C70CE315F299803AB6A00C7658B47      314          10466.0
6  1A052A833F4D5192008C5418EE6891C6      340          10371.0
7  83F8306463E117ED2BEF82E3C82939BD      323           9930.0
8  FE10081C77663C41F20939242E3A0C1B      376           9712.0
9  85AE3998D2019A2AF6218ED3DBF12317      389           9564.0

In [7]:
## Inspect most active vehicle

top_vehicle = con.execute("""
    SELECT vehicle_id FROM trips
    GROUP BY vehicle_id
    ORDER BY SUM(n_handovers) DESC
    LIMIT 1
""").fetchone()[0]

print(f"Vehicle: {top_vehicle}")
con.execute(f"""
    SELECT trip_id, trip_start, trip_end, duration_minutes,
           n_handovers, n_cells, cell_sequence
    FROM trips
    WHERE vehicle_id = '{top_vehicle}'
    ORDER BY trip_start
    LIMIT 20
""").df()

Vehicle: 0672B8A81103E3A99FA8878E0E81250F

,trip_id,trip_start,trip_end,duration_minutes,n_handovers,n_cells,cell_sequence
0,0672B8A81103E3A99FA8878E0E81250F_trip_001,2025-03-04 17:41:34.948,2025-03-04 23:52:35.281,371.0,43.0,38,136804618 -> 136804782 -> 136804782 -> 1368071...
1,0672B8A81103E3A99FA8878E0E81250F_trip_006,2025-03-05 05:23:13.770,2025-03-05 07:15:57.116,112.7,13.0,12,137232044 -> 137232044 -> 136870061 -> 1364256...
2,0672B8A81103E3A99FA8878E0E81250F_trip_011,2025-03-05 12:53:05.325,2025-03-05 23:55:17.410,662.2,79.0,71,137924874 -> 137924887 -> 136710316 -> 1368052...
3,0672B8A81103E3A99FA8878E0E81250F_trip_004,2025-03-06 11:04:30.898,2025-03-06 14:57:49.223,233.3,27.0,27,136560045 -> 136560045 -> 137925038 -> 1372626...
4,0672B8A81103E3A99FA8878E0E81250F_trip_005,2025-03-06 15:13:55.769,2025-03-06 21:41:02.826,387.1,44.0,41,138234376 -> 138163750 -> 138163978 -> 1370260...
5,0672B8A81103E3A99FA8878E0E81250F_trip_005,2025-03-07 04:37:23.227,2025-03-07 06:14:10.817,96.8,11.0,10,136560045 -> 136800430 -> 136707607 -> 1371521...
6,0672B8A81103E3A99FA8878E0E81250F_trip_006,2025-03-07 13:37:37.258,2025-03-07 15:22:25.174,104.8,13.0,13,137924874 -> 137924873 -> 136710317 -> 1376116...
7,0672B8A81103E3A99FA8878E0E81250F_trip_008,2025-03-07 18:35:39.583,2025-03-07 21:49:09.735,193.5,21.0,18,138085641 -> 136817069 -> 136790282 -> 1373063...
8,0672B8A81103E3A99FA8878E0E81250F_trip_001,2025-03-08 00:06:02.251,2025-03-08 01:50:51.577,104.8,10.0,10,137477219 -> 137477219 -> 136877834 -> 1381931...
9,0672B8A81103E3A99FA8878E0E81250F_trip_008,2025-03-10 14:27:07.020,2025-03-10 16:19:50.174,112.7,13.0,12,137478755 -> 136779182 -> 136779180 -> 1367791...
10,0672B8A81103E3A99FA8878E0E81250F_trip_010,2025-03-10 17:24:15.061,2025-03-10 19:09:12.676,105.0,12.0,12,136740887 -> 136444170 -> 136958892 -> 1369587...
11,0672B8A81103E3A99FA8878E0E81250F_trip_001,2025-03-11 00:07:15.570,2025-03-11 02:24:10.222,136.9,17.0,17,137232046 -> 135825679 -> 136803081 -> 1368593...
12,0672B8A81103E3A99FA8878E0E81250F_trip_007,2025-03-11 12:10:36.163,2025-03-11 18:05:03.831,354.5,42.0,42,136142857 -> 136142870 -> 136851885 -> 1368518...
13,0672B8A81103E3A99FA8878E0E81250F_trip_008,2025-03-11 18:29:13.040,2025-03-11 22:30:56.491,241.7,30.0,28,138126089 -> 137172233 -> 137172397 -> 1368138...
14,0672B8A81103E3A99FA8878E0E81250F_trip_001,2025-03-12 00:07:33.806,2025-03-12 01:28:05.370,80.5,10.0,10,136764937 -> 136861961 -> 136862124 -> 1368621...
15,0672B8A81103E3A99FA8878E0E81250F_trip_011,2025-03-12 18:29:17.098,2025-03-12 23:35:30.426,306.2,31.0,25,137474675 -> 137234968 -> 136741037 -> 1374772...
16,0672B8A81103E3A99FA8878E0E81250F_trip_007,2025-03-13 14:11:38.877,2025-03-13 15:40:20.748,88.7,10.0,10,136744201 -> 138187693 -> 136804781 -> 1372349...
17,0672B8A81103E3A99FA8878E0E81250F_trip_009,2025-03-13 18:21:22.871,2025-03-13 20:14:06.373,112.7,12.0,10,136869898 -> 136425483 -> 136769047 -> 1367690...
18,0672B8A81103E3A99FA8878E0E81250F_trip_011,2025-03-13 21:58:54.676,2025-03-13 23:59:42.641,120.8,16.0,15,137232046 -> 137200408 -> 137256200 -> 1382284...
19,0672B8A81103E3A99FA8878E0E81250F_trip_004,2025-03-14 02:46:39.223,2025-03-14 05:27:59.490,161.3,19.0,18,136870153 -> 136870317 -> 136710318 -> 1379248...

In [8]:
con.execute(f"""
    SELECT trip_id, trip_start, trip_end, duration_minutes,
           n_handovers, n_cells, cell_sequence
    FROM trips
    WHERE vehicle_id = 'A2FCC9AF8E480E683F655628A3E5E38D'
    ORDER BY trip_start
    LIMIT 20
""").df()

,trip_id,trip_start,trip_end,duration_minutes,n_handovers,n_cells,cell_sequence
0,A2FCC9AF8E480E683F655628A3E5E38D_trip_020,2025-05-19 18:32:40.767,2025-05-19 21:54:20.614,201.7,22.0,18,182074121 -> 182074129 -> 182074135 -> 1820741...
1,A2FCC9AF8E480E683F655628A3E5E38D_trip_011,2025-05-20 13:12:36.616,2025-05-20 16:05:23.307,172.8,28.0,13,182061079 -> 182017544 -> 9852418 -> 9852418 -...
2,A2FCC9AF8E480E683F655628A3E5E38D_trip_014,2025-05-21 20:38:35.053,2025-05-21 22:50:49.289,132.2,16.0,14,182033161 -> 182714890 -> 182016264 -> 1820339...
3,A2FCC9AF8E480E683F655628A3E5E38D_trip_008,2025-05-22 20:46:20.868,2025-05-22 22:24:42.778,98.4,15.0,10,182035990 -> 182322198 -> 9852418 -> 182017551...
4,A2FCC9AF8E480E683F655628A3E5E38D_trip_009,2025-05-22 22:40:49.059,2025-05-22 23:53:30.694,72.7,10.0,10,182035978 -> 182322198 -> 182061079 -> 1820610...
5,A2FCC9AF8E480E683F655628A3E5E38D_trip_001,2025-05-23 00:01:33.506,2025-05-23 02:26:27.334,144.9,17.0,17,182712329 -> 181819401 -> 181853464 -> 1827517...
6,A2FCC9AF8E480E683F655628A3E5E38D_trip_003,2025-05-25 10:14:21.650,2025-05-25 15:39:17.954,324.9,42.0,37,185806600 -> 185379849 -> 185163273 -> 1853847...
7,A2FCC9AF8E480E683F655628A3E5E38D_trip_010,2025-05-26 19:12:47.145,2025-05-26 21:29:35.196,136.8,14.0,10,182321936 -> 182321928 -> 182321943 -> 1823219...
8,A2FCC9AF8E480E683F655628A3E5E38D_trip_017,2025-05-28 19:55:42.027,2025-05-28 22:28:28.214,152.8,20.0,11,182035990 -> 182035978 -> 182035977 -> 1818396...
9,A2FCC9AF8E480E683F655628A3E5E38D_trip_014,2025-06-05 19:12:39.192,2025-06-05 22:26:50.963,194.2,15.0,10,182187018 -> 182187032 -> 182187032 -> 1823116...
10,A2FCC9AF8E480E683F655628A3E5E38D_trip_013,2025-06-08 13:52:23.895,2025-06-08 15:48:32.066,116.2,16.0,11,182061079 -> 9852418 -> 9852478 -> 182061079 -...
11,A2FCC9AF8E480E683F655628A3E5E38D_trip_014,2025-06-08 16:04:38.647,2025-06-08 17:25:06.517,80.5,10.0,10,182042377 -> 182055447 -> 182048534 -> 1820741...
12,A2FCC9AF8E480E683F655628A3E5E38D_trip_016,2025-06-08 18:29:28.081,2025-06-08 23:11:31.217,282.1,29.0,14,45016328 -> 45006614 -> 45008137 -> 45064728 -...
13,A2FCC9AF8E480E683F655628A3E5E38D_trip_009,2025-06-10 12:33:37.494,2025-06-10 15:31:28.913,177.9,20.0,20,45155806 -> 45123594 -> 43589642 -> 43920138 -...
14,A2FCC9AF8E480E683F655628A3E5E38D_trip_010,2025-06-13 22:12:19.990,2025-06-13 23:49:08.014,96.8,13.0,12,182016266 -> 182030858 -> 182042392 -> 1820585...
15,A2FCC9AF8E480E683F655628A3E5E38D_trip_005,2025-06-14 14:02:34.555,2025-06-14 15:31:05.320,88.5,11.0,10,182035991 -> 182035978 -> 182035991 -> 1820610...
16,A2FCC9AF8E480E683F655628A3E5E38D_trip_007,2025-06-16 15:44:20.084,2025-06-16 18:08:31.399,144.2,17.0,12,182061079 -> 182061079 -> 182061079 -> 9852418...
17,A2FCC9AF8E480E683F655628A3E5E38D_trip_012,2025-06-22 17:10:08.655,2025-06-22 18:59:44.549,109.6,15.0,13,9852418 -> 182061079 -> 9852418 -> 182017559 -...
18,A2FCC9AF8E480E683F655628A3E5E38D_trip_013,2025-06-22 19:23:52.295,2025-06-22 21:39:06.431,135.2,26.0,13,182187017 -> 182187018 -> 182187018 -> 1823219...
19,A2FCC9AF8E480E683F655628A3E5E38D_trip_010,2025-06-23 18:44:26.141,2025-06-23 23:58:49.698,314.4,33.0,23,181877770 -> 182027530 -> 182016535 -> 1818793...

In [9]:
# Export trips for one vehicle safely (avoid loading all rows into pandas)
from pathlib import Path

target_vehicle = 'A2FCC9AF8E480E683F655628A3E5E38D'
export_dir = Path('/home/jovyan/data/exports/trips')
export_dir.mkdir(parents=True, exist_ok=True)

out_parquet = export_dir / f'{target_vehicle}_all_trips.parquet'
out_excel = export_dir / f'{target_vehicle}_all_trips.xlsx'

total_rows = con.execute(f"""
    SELECT COUNT(*)
    FROM trips
    WHERE vehicle_id = '{target_vehicle}'
""").fetchone()[0]

print(f"Vehicle {target_vehicle} has {total_rows:,} trip rows")

# Full export path that does not materialize all rows in Python memory.
con.execute(f"""
    COPY (
        SELECT
            trip_id, trip_start, trip_end, duration_minutes,
            n_handovers, n_cells, cell_sequence
        FROM trips
        WHERE vehicle_id = '{target_vehicle}'
        ORDER BY trip_start
    ) TO '{out_parquet}' (FORMAT PARQUET)
""")
print(f"Full parquet export written: {out_parquet}")

# Excel export is capped to keep kernel memory stable.
EXCEL_MAX_ROWS = 200_000
if total_rows > EXCEL_MAX_ROWS:
    print(
        f"Capping Excel export to first {EXCEL_MAX_ROWS:,} rows to avoid kernel OOM "
        f"(full data is in parquet)."
    )

excel_df = con.execute(f"""
    SELECT
        trip_id, trip_start, trip_end, duration_minutes,
        n_handovers, n_cells, cell_sequence
    FROM trips
    WHERE vehicle_id = '{target_vehicle}'
    ORDER BY trip_start
    LIMIT {EXCEL_MAX_ROWS}
""").df()

excel_df.to_excel(out_excel, index=False)
print(f"Excel export written: {out_excel} ({len(excel_df):,} rows)")

del excel_df

Vehicle A2FCC9AF8E480E683F655628A3E5E38D has 88 trip rows
Full parquet export written: /home/jovyan/data/exports/trips/A2FCC9AF8E480E683F655628A3E5E38D_all_trips.parquet
Excel export written: /home/jovyan/data/exports/trips/A2FCC9AF8E480E683F655628A3E5E38D_all_trips.xlsx (88 rows)

In [10]:
con.execute("""
    SELECT MIN(event_date), MAX(event_date), COUNT(DISTINCT event_date)
    FROM trips
""").df()

  min(event_date) max(event_date)  count(DISTINCT event_date)
0      2025-01-04      2025-12-31                         352

In [11]:
## Visualisations (memory-safe + progress logging)

import time
import plotly.express as px
import plotly.graph_objects as go

viz_start = time.time()

def _log(step: str):
    elapsed = time.time() - viz_start
    print(f"[{elapsed:6.1f}s] {step}")

TRIPS_SOURCE = "trips"
_log("Starting visualisations...")

overview = con.execute(f"""
    SELECT
        COUNT(*) AS n_trips,
        COUNT(DISTINCT vehicle_id) AS n_vehicles,
        MIN(event_date) AS first_date,
        MAX(event_date) AS last_date
    FROM {TRIPS_SOURCE}
""").df()

print(
    f"Total trips: {int(overview.loc[0, 'n_trips']):,} | "
    f"Vehicles: {int(overview.loc[0, 'n_vehicles']):,} | "
    f"Range: {overview.loc[0, 'first_date']} to {overview.loc[0, 'last_date']}"
)

# 1) Daily trip volume
_log("Querying daily trip volume...")
daily = con.execute(f"""
    SELECT event_date, COUNT(*) AS n_trips
    FROM {TRIPS_SOURCE}
    GROUP BY event_date
    ORDER BY event_date
""").df()

_log("Rendering daily trip volume chart...")
fig1 = px.line(
    daily, x='event_date', y='n_trips',
    title='Daily Trip Volume — Full Year',
    labels={'event_date': 'Date', 'n_trips': 'Trips'}
)
fig1.update_traces(line_width=1.2)
fig1.update_layout(hovermode='x unified')
fig1.show()

# 2) Hourly departure heatmap
_log("Querying hour x weekday matrix...")
heatmap_data = con.execute(f"""
    SELECT
        EXTRACT(DOW FROM trip_start)::INT AS weekday_n,
        CASE EXTRACT(DOW FROM trip_start)::INT
            WHEN 0 THEN 'Sunday'
            WHEN 1 THEN 'Monday'
            WHEN 2 THEN 'Tuesday'
            WHEN 3 THEN 'Wednesday'
            WHEN 4 THEN 'Thursday'
            WHEN 5 THEN 'Friday'
            ELSE 'Saturday'
        END AS weekday,
        EXTRACT(HOUR FROM trip_start)::INT AS hour,
        COUNT(*) AS n_trips
    FROM {TRIPS_SOURCE}
    GROUP BY 1, 2, 3
    ORDER BY 1, 3
""").df()

pivot = heatmap_data.pivot(index='weekday', columns='hour', values='n_trips').fillna(0)
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
pivot = pivot.reindex([d for d in day_order if d in pivot.index])

_log("Rendering heatmap...")
fig2 = go.Figure(go.Heatmap(
    z=pivot.values,
    x=pivot.columns.tolist(),
    y=pivot.index.tolist(),
    colorscale='Viridis',
    colorbar=dict(title='Trips')
))
fig2.update_layout(
    title='Trip Departures — Hour of Day x Day of Week',
    xaxis_title='Hour',
    yaxis_title='Weekday',
)
fig2.show()

# 3) Trip duration distribution (pre-binned in SQL)
_log("Querying duration histogram bins...")
duration_hist = con.execute(f"""
    WITH clipped AS (
        SELECT duration_minutes
        FROM {TRIPS_SOURCE}
        WHERE duration_minutes BETWEEN 1 AND 240
    )
    SELECT
        FLOOR(duration_minutes / 3)::INT * 3 AS bin_start_min,
        COUNT(*) AS n_trips
    FROM clipped
    GROUP BY 1
    ORDER BY 1
""").df()

_log("Rendering duration distribution...")
fig3 = px.bar(
    duration_hist, x='bin_start_min', y='n_trips',
    title='Trip Duration Distribution (1-240 min, 3-min bins)',
    labels={'bin_start_min': 'Duration bin start (min)', 'n_trips': 'Trips'},
    color_discrete_sequence=['steelblue']
 )
fig3.show()

# 4) Handovers distribution (pre-binned in SQL)
_log("Querying handover histogram bins...")
handover_hist = con.execute(f"""
    WITH clipped AS (
        SELECT n_handovers
        FROM {TRIPS_SOURCE}
        WHERE n_handovers <= 200
    )
    SELECT
        n_handovers AS handover_bin,
        COUNT(*) AS n_trips
    FROM clipped
    GROUP BY 1
    ORDER BY 1
""").df()

_log("Rendering handovers distribution...")
fig4 = px.bar(
    handover_hist, x='handover_bin', y='n_trips',
    title='Handovers per Trip Distribution (<=200)',
    labels={'handover_bin': 'Handovers', 'n_trips': 'Trips'},
    color_discrete_sequence=['coral']
 )
fig4.show()

# 5) RAT mix over time
_log("Querying RAT monthly mix...")
rat_monthly = con.execute(f"""
    SELECT
        STRFTIME(trip_start, '%Y-%m') AS month,
        COALESCE(dominant_rat, 'Unknown') AS dominant_rat,
        COUNT(*) AS n_trips
    FROM {TRIPS_SOURCE}
    GROUP BY 1, 2
    ORDER BY 1, 2
""").df()

_log("Rendering RAT monthly mix...")
fig5 = px.bar(
    rat_monthly, x='month', y='n_trips', color='dominant_rat',
    title='Monthly Trip Volume by Dominant RAT (4G / 5G)',
    labels={'month': 'Month', 'n_trips': 'Trips', 'dominant_rat': 'RAT'},
    barmode='stack'
 )
fig5.update_layout(xaxis_tickangle=-45)
fig5.show()

# 6) Top 20 vehicles by handovers
_log("Querying top 20 vehicles...")
top20 = con.execute(f"""
    SELECT
        vehicle_id,
        COUNT(*) AS n_trips,
        SUM(n_handovers) AS total_handovers
    FROM {TRIPS_SOURCE}
    GROUP BY vehicle_id
    ORDER BY total_handovers DESC
    LIMIT 20
""").df()

_log("Rendering top 20 vehicles chart...")
fig6 = px.bar(
    top20, x='vehicle_id', y='total_handovers', color='n_trips',
    title='Top-20 Vehicles by Total Handovers',
    labels={'vehicle_id': 'Vehicle', 'total_handovers': 'Total Handovers', 'n_trips': 'Trips'},
    color_continuous_scale='Blues'
 )
fig6.update_layout(xaxis_tickangle=-60, xaxis_tickfont_size=9)
fig6.show()

# 7) Duration vs Handovers scatter (small DB-side sample only)
_log("Querying scatter sample (max 5k rows)...")
sample = con.execute(f"""
    SELECT
        duration_minutes,
        n_handovers,
        COALESCE(dominant_rat, 'Unknown') AS dominant_rat
    FROM {TRIPS_SOURCE}
    WHERE duration_minutes BETWEEN 1 AND 240
    USING SAMPLE 5000 ROWS
""").df()

_log(f"Rendering scatter ({len(sample):,} rows)...")
fig7 = px.scatter(
    sample, x='duration_minutes', y='n_handovers',
    color='dominant_rat', opacity=0.4,
    title='Trip Duration vs Handovers (sample)',
    labels={
        'duration_minutes': 'Duration (min)',
        'n_handovers': 'Handovers',
        'dominant_rat': 'RAT'
    }
)
fig7.show()

_log("Visualisations complete.")

[   0.0s] Starting visualisations...
Total trips: 2,085,238 | Vehicles: 93,359 | Range: 2025-01-04 00:00:00 to 2025-12-31 00:00:00
[   0.0s] Querying daily trip volume...
[   0.0s] Rendering daily trip volume chart...

[   0.5s] Querying hour x weekday matrix...
[   0.5s] Rendering heatmap...

[   0.5s] Querying duration histogram bins...
[   0.5s] Rendering duration distribution...

[   0.5s] Querying handover histogram bins...
[   0.6s] Rendering handovers distribution...

[   0.6s] Querying RAT monthly mix...
[   0.6s] Rendering RAT monthly mix...

[   0.6s] Querying top 20 vehicles...
[   0.7s] Rendering top 20 vehicles chart...

[   0.8s] Querying scatter sample (max 5k rows)...
[   0.8s] Rendering scatter (4,382 rows)...

[   0.8s] Visualisations complete.