# Staging — DuckDB Native

Replaces the pandas row-by-row CSV reader with DuckDB's `read_csv` which is
orders of magnitude faster.

- **Resumable** — skips files already staged (checks for existing parquet)
- **No destructive reset** — never wipes the stage folder
- **Controllable** — set `MAX_FILES` to limit how many files are processed

In [1]:
## Config

import duckdb
import os
from pathlib import Path
import time

RAW_DIR   = Path("/home/jovyan/data/sim/raw/sim_test_decoded/2025/")
STAGE_DIR = Path("/home/jovyan/data/stage/handover_events")
TMP_DIR   = "/home/jovyan/data/tmp"

# Column positions (zero-based) in the raw CSV
# id, test_type, creation_time, collection_time, insert_time, sim_id, ...
COL_EVENT_TS   = '03'   # collection_time
COL_VEHICLE_ID = '05'   # sim_id
COL_IMSI       = '13' # imsi
COL_CELL_ID    = '18' # cell_id
COL_RAT        = '23' # technology (4G/5G)


# Set to an integer to limit files processed (useful for testing)
# Set to None to process all files
MAX_FILES = None

STAGE_DIR.mkdir(parents=True, exist_ok=True)
os.makedirs(TMP_DIR, exist_ok=True)

print(f"RAW_DIR:   {RAW_DIR}")
print(f"STAGE_DIR: {STAGE_DIR}")
print(f"MAX_FILES: {MAX_FILES}")

RAW_DIR:   /home/jovyan/data/sim/raw/sim_test_decoded/2025
STAGE_DIR: /home/jovyan/data/stage/handover_events
MAX_FILES: None

In [2]:
## Connect DuckDB

con = duckdb.connect()  # in-memory — staging doesn't need persistence
con.execute(f"SET temp_directory='{TMP_DIR}'")
con.execute("SET memory_limit='8GB'")
con.execute("SET threads=8")

import os, psutil
print(f"CPUs: {os.cpu_count()}")
print(f"RAM:  {round(psutil.virtual_memory().total / (1024**3), 1)} GB")

CPUs: 24
RAM:  39.0 GB

In [3]:
## Find raw files

exts = {".gz", ".csv", ".txt"}
all_files = sorted([
    p for p in RAW_DIR.rglob("*")
    if p.is_file() and p.suffix.lower() in exts
])

raw_files = all_files[:MAX_FILES] if MAX_FILES else all_files

print(f"Total files found: {len(all_files)}")
print(f"Files to consider: {len(raw_files)}")

Total files found: 304
Files to consider: 304

In [4]:
## Process files — resumable, DuckDB native

skipped = 0
processed = 0
total_good = 0
total_bad = 0
run_start = time.time()

for i, path in enumerate(raw_files, 1):

    # Derive the expected output path from the filename date
    # e.g. 2025_06_15.txt -> event_date=2025-06-15
    stem = path.stem  # e.g. '2025_06_15'
    event_date = stem.replace('_', '-')  # e.g. '2025-06-15'
    out_dir  = STAGE_DIR / f"event_date={event_date}"
    out_file = out_dir / "stage.parquet"

    # --- Resumable: skip if already staged ---
    if out_file.exists():
        skipped += 1
        print(f"[{i}/{len(raw_files)}] SKIP {path.name}")
        continue

    file_start = time.time()

    try:
        out_dir.mkdir(parents=True, exist_ok=True)

        # DuckDB reads the CSV and writes parquet in one shot
        # column0..columnN maps to zero-based column positions
        result = con.execute(f"""
            COPY (
                SELECT
                    column{COL_VEHICLE_ID}  AS vehicle_id,
                    column{COL_IMSI}        AS imsi,
                    column{COL_EVENT_TS}    AS event_ts,
                    column{COL_CELL_ID}     AS cell_id,
                    column{COL_RAT}         AS rat,
                    '{path.name}'           AS source_file
                FROM read_csv(
                    '{path}',
                    header        = false,
                    ignore_errors = true,
                    compression   = 'auto',
                    delim         = ','
                )
                WHERE column{COL_VEHICLE_ID} IS NOT NULL
                  AND column{COL_CELL_ID}    IS NOT NULL
                  AND column{COL_EVENT_TS}   IS NOT NULL
            ) TO '{out_file}' (FORMAT PARQUET)
        """)

        elapsed = time.time() - file_start
        # Count rows written
        n_rows = con.execute(f"SELECT COUNT(*) FROM read_parquet('{out_file}')").fetchone()[0]
        total_good += n_rows
        processed += 1
        print(f"[{i}/{len(raw_files)}] {path.name} → {n_rows:,} rows ({elapsed:.1f}s)")

    except Exception as e:
        total_bad += 1
        print(f"[{i}/{len(raw_files)}] ERROR {path.name}: {e}")

total_elapsed = time.time() - run_start
print(f"\nDone. {processed} processed, {skipped} skipped, {total_bad} errors")
print(f"Total rows staged: {total_good:,}")
print(f"Total runtime: {total_elapsed/60:.1f} min")

[1/304] SKIP 2025_01_01.gz
[2/304] SKIP 2025_01_02.gz
[3/304] SKIP 2025_01_03.gz
[4/304] SKIP 2025_01_04.gz
[5/304] SKIP 2025_01_05.gz
[6/304] SKIP 2025_01_06.gz
[7/304] SKIP 2025_01_07.gz
[8/304] SKIP 2025_01_08.gz
[9/304] SKIP 2025_01_09.gz
[10/304] SKIP 2025_01_10.gz
[11/304] SKIP 2025_01_11.gz
[12/304] SKIP 2025_01_12.gz
[13/304] SKIP 2025_01_13.gz
[14/304] SKIP 2025_01_14.gz
[15/304] SKIP 2025_01_15.gz
[16/304] SKIP 2025_01_17.gz
[17/304] SKIP 2025_01_18.gz
[18/304] SKIP 2025_01_19.gz
[19/304] SKIP 2025_01_20.gz
[20/304] SKIP 2025_01_21.gz
[21/304] SKIP 2025_01_22.gz
[22/304] SKIP 2025_01_23.gz
[23/304] SKIP 2025_01_24.gz
[24/304] SKIP 2025_01_25.gz
[25/304] SKIP 2025_01_26.gz
[26/304] SKIP 2025_01_27.gz
[27/304] SKIP 2025_01_28.gz
[28/304] SKIP 2025_01_29.gz
[29/304] SKIP 2025_01_30.gz
[30/304] SKIP 2025_01_31.gz
[31/304] SKIP 2025_02_01.gz
[32/304] SKIP 2025_02_02.gz
[33/304] SKIP 2025_02_03.gz
[34/304] SKIP 2025_02_04.gz
[35/304] SKIP 2025_02_05.gz
[36/304] SKIP 2025_02_06.gz
[37/304] SKIP 2025_02_07.gz
[38/304] SKIP 2025_02_08.gz
[39/304] SKIP 2025_02_09.gz
[40/304] SKIP 2025_02_10.gz
[41/304] SKIP 2025_02_11.gz
[42/304] SKIP 2025_02_12.gz
[43/304] SKIP 2025_02_13.gz
[44/304] SKIP 2025_02_14.gz
[45/304] SKIP 2025_02_15.gz
[46/304] SKIP 2025_02_16.gz
[47/304] SKIP 2025_02_17.gz
[48/304] SKIP 2025_02_18.gz
[49/304] SKIP 2025_02_19.gz
[50/304] SKIP 2025_02_20.gz
[51/304] SKIP 2025_02_21.gz
[52/304] SKIP 2025_02_22.gz
[53/304] SKIP 2025_02_23.gz
[54/304] SKIP 2025_02_24.gz
[55/304] SKIP 2025_02_25.gz
[56/304] SKIP 2025_02_26.gz
[57/304] SKIP 2025_02_27.gz
[58/304] SKIP 2025_02_28.gz
[59/304] SKIP 2025_03_01.gz
[60/304] SKIP 2025_03_02.gz
[61/304] SKIP 2025_03_03.gz
[62/304] SKIP 2025_03_04.gz
[63/304] SKIP 2025_03_05.gz
[64/304] SKIP 2025_03_06.gz
[65/304] SKIP 2025_03_07.gz
[66/304] SKIP 2025_03_08.gz
[67/304] SKIP 2025_03_09.gz
[68/304] SKIP 2025_03_10.gz
[69/304] SKIP 2025_03_11.gz
[70/304] SKIP 2025_03_12.gz
[71/304] SKIP 2025_03_13.gz
[72/304] SKIP 2025_03_14.gz
[73/304] SKIP 2025_03_15.gz
[74/304] SKIP 2025_03_16.gz
[75/304] SKIP 2025_03_17.gz
[76/304] SKIP 2025_03_18.gz
[77/304] SKIP 2025_03_19.gz
[78/304] SKIP 2025_03_20.gz
[79/304] SKIP 2025_03_21.gz
[80/304] SKIP 2025_03_22.gz
[81/304] SKIP 2025_03_23.gz
[82/304] SKIP 2025_03_24.gz
[83/304] SKIP 2025_03_25.gz
[84/304] SKIP 2025_03_26.gz
[85/304] SKIP 2025_03_27.gz
[86/304] SKIP 2025_03_28.gz
[87/304] SKIP 2025_03_29.gz
[88/304] SKIP 2025_03_30.gz
[89/304] SKIP 2025_03_31.gz
[90/304] SKIP 2025_04_01.gz
[91/304] SKIP 2025_04_02.gz
[92/304] SKIP 2025_04_03.gz
[93/304] SKIP 2025_04_04.gz
[94/304] SKIP 2025_04_05.gz
[95/304] SKIP 2025_04_06.gz
[96/304] SKIP 2025_04_07.gz
[97/304] SKIP 2025_04_08.gz
[98/304] SKIP 2025_04_09.gz
[99/304] SKIP 2025_04_10.gz
[100/304] SKIP 2025_04_11.gz
[101/304] SKIP 2025_04_12.gz
[102/304] SKIP 2025_04_13.gz
[103/304] SKIP 2025_04_14.gz
[104/304] SKIP 2025_04_15.gz
[105/304] SKIP 2025_04_16.gz
[106/304] SKIP 2025_04_17.gz
[107/304] SKIP 2025_04_18.gz
[108/304] SKIP 2025_04_19.gz
[109/304] SKIP 2025_04_20.gz
[110/304] SKIP 2025_04_21.gz
[111/304] SKIP 2025_04_22.gz
[112/304] SKIP 2025_04_23.gz
[113/304] SKIP 2025_04_24.gz
[114/304] SKIP 2025_04_25.gz
[115/304] SKIP 2025_04_26.gz
[116/304] SKIP 2025_04_27.gz
[117/304] SKIP 2025_04_28.gz
[118/304] SKIP 2025_04_29.gz
[119/304] SKIP 2025_04_30.gz
[120/304] SKIP 2025_05_01.gz
[121/304] SKIP 2025_05_02.gz
[122/304] SKIP 2025_05_03.gz

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[123/304] 2025_05_04.gz → 2,617,428 rows (10.1s)
[124/304] SKIP 2025_05_05.gz
[125/304] SKIP 2025_05_06.gz

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[126/304] 2025_05_07.gz → 2,560,922 rows (12.4s)
[127/304] SKIP 2025_05_08.gz
[128/304] SKIP 2025_05_09.gz
[129/304] SKIP 2025_05_10.gz
[130/304] SKIP 2025_05_11.gz
[131/304] SKIP 2025_05_12.gz
[132/304] SKIP 2025_05_13.gz
[133/304] SKIP 2025_05_14.gz
[134/304] SKIP 2025_05_15.gz
[135/304] SKIP 2025_05_16.gz
[136/304] SKIP 2025_05_17.gz
[137/304] SKIP 2025_05_18.gz
[138/304] SKIP 2025_05_19.gz
[139/304] SKIP 2025_05_20.gz
[140/304] SKIP 2025_05_21.gz
[141/304] SKIP 2025_05_22.gz
[142/304] SKIP 2025_05_23.gz
[143/304] SKIP 2025_05_24.gz
[144/304] SKIP 2025_05_25.gz
[145/304] SKIP 2025_05_26.gz
[146/304] SKIP 2025_05_27.gz
[147/304] SKIP 2025_05_28.gz
[148/304] SKIP 2025_05_29.gz
[149/304] SKIP 2025_05_30.gz
[150/304] SKIP 2025_05_31.gz
[151/304] SKIP 2025_06_01.gz
[152/304] SKIP 2025_06_02.gz
[153/304] SKIP 2025_06_03.gz
[154/304] SKIP 2025_06_04.gz
[155/304] SKIP 2025_06_05.gz
[156/304] SKIP 2025_06_06.gz
[157/304] SKIP 2025_06_07.gz
[158/304] SKIP 2025_06_08.gz
[159/304] SKIP 2025_06_09.gz
[160/304] SKIP 2025_06_10.gz
[161/304] SKIP 2025_06_11.gz
[162/304] SKIP 2025_06_12.gz
[163/304] SKIP 2025_06_13.gz
[164/304] SKIP 2025_06_14.gz
[165/304] SKIP 2025_06_15.gz
[166/304] SKIP 2025_06_16.gz
[167/304] SKIP 2025_06_17.gz
[168/304] SKIP 2025_06_18.gz
[169/304] SKIP 2025_06_19.gz
[170/304] SKIP 2025_06_20.gz
[171/304] SKIP 2025_06_21.gz
[172/304] SKIP 2025_06_22.gz
[173/304] SKIP 2025_06_23.gz
[174/304] SKIP 2025_06_24.gz
[175/304] SKIP 2025_06_25.gz
[176/304] SKIP 2025_06_26.gz
[177/304] SKIP 2025_06_27.gz
[178/304] SKIP 2025_06_28.gz
[179/304] SKIP 2025_06_29.gz
[180/304] SKIP 2025_06_30.gz
[181/304] SKIP 2025_07_01.gz
[182/304] SKIP 2025_07_02.gz
[183/304] SKIP 2025_07_03.gz
[184/304] SKIP 2025_07_04.gz
[185/304] SKIP 2025_07_05.gz
[186/304] SKIP 2025_07_06.gz
[187/304] SKIP 2025_07_07.gz
[188/304] SKIP 2025_07_08.gz
[189/304] SKIP 2025_07_09.gz
[190/304] SKIP 2025_07_10.gz
[191/304] SKIP 2025_07_11.gz
[192/304] SKIP 2025_07_12.gz
[193/304] SKIP 2025_07_13.gz
[194/304] SKIP 2025_07_14.gz
[195/304] SKIP 2025_07_15.gz
[196/304] SKIP 2025_07_16.gz
[197/304] SKIP 2025_07_17.gz
[198/304] SKIP 2025_07_18.gz
[199/304] SKIP 2025_07_19.gz
[200/304] SKIP 2025_07_20.gz
[201/304] SKIP 2025_07_21.gz
[202/304] SKIP 2025_07_22.gz
[203/304] SKIP 2025_07_23.gz
[204/304] SKIP 2025_07_24.gz
[205/304] SKIP 2025_07_25.gz
[206/304] SKIP 2025_07_26.gz
[207/304] SKIP 2025_07_27.gz
[208/304] SKIP 2025_07_28.gz
[209/304] SKIP 2025_07_29.gz
[210/304] SKIP 2025_07_30.gz
[211/304] SKIP 2025_07_31.gz
[212/304] SKIP 2025_08_01.gz
[213/304] SKIP 2025_08_02.gz
[214/304] SKIP 2025_08_03.gz
[215/304] SKIP 2025_08_04.gz
[216/304] SKIP 2025_08_05.gz
[217/304] SKIP 2025_08_06.gz
[218/304] SKIP 2025_08_07.gz
[219/304] SKIP 2025_08_08.gz
[220/304] SKIP 2025_08_09.gz
[221/304] SKIP 2025_08_10.gz
[222/304] SKIP 2025_08_11.gz
[223/304] SKIP 2025_08_12.gz
[224/304] SKIP 2025_08_13.gz
[225/304] SKIP 2025_08_14.gz
[226/304] SKIP 2025_08_15.gz
[227/304] SKIP 2025_08_16.gz
[228/304] SKIP 2025_08_17.gz
[229/304] SKIP 2025_08_18.gz
[230/304] SKIP 2025_08_19.gz
[231/304] SKIP 2025_08_20.gz
[232/304] SKIP 2025_08_21.gz
[233/304] SKIP 2025_08_22.gz
[234/304] SKIP 2025_08_23.gz
[235/304] SKIP 2025_08_24.gz
[236/304] SKIP 2025_08_25.gz
[237/304] SKIP 2025_08_26.gz
[238/304] SKIP 2025_08_27.gz
[239/304] SKIP 2025_08_28.gz
[240/304] SKIP 2025_08_29.gz
[241/304] SKIP 2025_08_30.gz
[242/304] SKIP 2025_08_31.gz
[243/304] SKIP 2025_09_01.gz
[244/304] SKIP 2025_09_02.gz
[245/304] SKIP 2025_09_03.gz
[246/304] SKIP 2025_09_04.gz
[247/304] SKIP 2025_09_05.gz
[248/304] SKIP 2025_09_06.gz
[249/304] SKIP 2025_09_07.gz
[250/304] SKIP 2025_09_08.gz
[251/304] SKIP 2025_09_09.gz
[252/304] SKIP 2025_09_10.gz
[253/304] SKIP 2025_09_11.gz
[254/304] SKIP 2025_09_12.gz
[255/304] SKIP 2025_09_13.gz
[256/304] SKIP 2025_09_14.gz
[257/304] SKIP 2025_09_15.gz
[258/304] SKIP 2025_09_16.gz
[259/304] SKIP 2025_09_17.gz
[260/304] SKIP 2025_09_18.gz
[261/304] SKIP 2025_09_19.gz
[262/304] SKIP 2025_09_20.gz
[263/304] SKIP 2025_09_21.gz
[264/304] SKIP 2025_09_22.gz
[265/304] SKIP 2025_09_23.gz
[266/304] SKIP 2025_09_24.gz
[267/304] SKIP 2025_09_25.gz
[268/304] SKIP 2025_09_26.gz
[269/304] SKIP 2025_09_27.gz
[270/304] SKIP 2025_09_28.gz
[271/304] SKIP 2025_09_29.gz
[272/304] SKIP 2025_09_30.gz
[273/304] SKIP 2025_10_01.gz
[274/304] SKIP 2025_10_02.gz
[275/304] SKIP 2025_10_03.gz
[276/304] SKIP 2025_10_04.gz
[277/304] SKIP 2025_10_05.gz
[278/304] SKIP 2025_10_06.gz
[279/304] SKIP 2025_10_07.gz
[280/304] SKIP 2025_10_08.gz
[281/304] SKIP 2025_10_09.gz
[282/304] SKIP 2025_10_10.gz
[283/304] SKIP 2025_10_11.gz
[284/304] SKIP 2025_10_12.gz
[285/304] SKIP 2025_10_13.gz
[286/304] SKIP 2025_10_14.gz
[287/304] SKIP 2025_10_15.gz
[288/304] SKIP 2025_10_16.gz
[289/304] SKIP 2025_10_17.gz
[290/304] SKIP 2025_10_18.gz
[291/304] SKIP 2025_10_19.gz
[292/304] SKIP 2025_10_20.gz
[293/304] SKIP 2025_10_21.gz
[294/304] SKIP 2025_10_22.gz
[295/304] SKIP 2025_10_23.gz
[296/304] SKIP 2025_10_24.gz
[297/304] SKIP 2025_10_25.gz
[298/304] SKIP 2025_10_26.gz
[299/304] SKIP 2025_10_27.gz
[300/304] SKIP 2025_10_28.gz
[301/304] SKIP 2025_10_29.gz
[302/304] SKIP 2025_10_30.gz
[303/304] SKIP 2025_10_31.gz
[304/304] SKIP 2025_11_01.gz

Done. 2 processed, 302 skipped, 0 errors
Total rows staged: 5,178,350
Total runtime: 0.4 min

In [5]:
## Verify — check a sample parquet file

sample_files = list(STAGE_DIR.rglob("*.parquet"))
print(f"Parquet files on disk: {len(sample_files)}")

con.execute(f"""
    SELECT *
    FROM read_parquet('{sample_files[0]}')
    LIMIT 3
""").df()

Parquet files on disk: 418

,vehicle_id,imsi,event_ts,cell_id,rat,source_file,event_date
0,F140A413CDBACB245F79DAE1D7438EC4,000000000000000,2025-01-01 00:02:01.793,69492489,4G,2025_01_01.gz,2025-01-01
1,F140A413CDBACB245F79DAE1D7438EC4,000000000000000,2025-01-01 00:10:05.626,69492489,4G,2025_01_01.gz,2025-01-01
2,F140A413CDBACB245F79DAE1D7438EC4,000000000000000,2025-01-01 00:18:09.436,69492708,4G,2025_01_01.gz,2025-01-01

In [6]:
## Register handover_events in analytics DuckDB

analytics = duckdb.connect("/home/jovyan/data/analytics.duckdb")
analytics.execute("SET memory_limit='8GB'")

analytics.execute("DROP TABLE IF EXISTS handover_events")
analytics.execute(f"""
    CREATE TABLE handover_events AS
    SELECT
        vehicle_id,
        imsi,
        event_ts,
        cell_id,
        rat,
        source_file,
        CAST(event_ts AS DATE) AS event_date
    FROM read_parquet('{STAGE_DIR}/**/*.parquet')
    WHERE vehicle_id IS NOT NULL
      AND cell_id    IS NOT NULL
      AND event_ts   IS NOT NULL
""")

analytics.execute("""
    SELECT
        COUNT(*)                   AS total_rows,
        COUNT(DISTINCT vehicle_id) AS vehicles,
        COUNT(DISTINCT cell_id)    AS cells,
        MIN(event_ts)              AS min_event,
        MAX(event_ts)              AS max_event
    FROM handover_events
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,total_rows,vehicles,cells,min_event,max_event
0,913539144,99610,941090,2025-01-01 00:02:01.793,2025-11-01 23:59:56.110