# Staging â€” DuckDB Native

Replaces the pandas row-by-row CSV reader with DuckDB's `read_csv` which is
orders of magnitude faster.

- **Resumable** â€” skips files already staged (checks for existing parquet)
- **No destructive reset** â€” never wipes the stage folder
- **Controllable** â€” set `MAX_FILES` to limit how many files are processed

In [7]:
## Config

import duckdb
import json
import os
from pathlib import Path
import time

RAW_DIR   = Path("/home/jovyan/data/sim/raw/sim_test_decoded/2025/")
STAGE_DIR = Path("/home/jovyan/data/stage/handover_events")
# Use native Linux filesystem for DuckDB temp spill â€” mmap works here,
# unlike the Windows NTFS mount at /home/jovyan/data/
TMP_DIR   = "/tmp/duckdb_tmp"

# Column positions (zero-based) in the raw CSV
# id, test_type, creation_time, collection_time, insert_time, sim_id, ...
COL_EVENT_TS   = '03'   # collection_time
COL_VEHICLE_ID = '05'   # sim_id
COL_IMSI       = '13' # imsi
COL_CELL_ID    = '18' # cell_id
COL_RAT        = '23' # technology (4G/5G)
COL_PCI1_RSRP  = '34'  # pci_1_rsrp  — neighbour cell RSRP
COL_PCI1_RSRQ  = '35'  # pci_1_rsrq  — neighbour cell RSRQ
COL_PING1      = '84'  # ping1
COL_PING2      = '85'  # ping2
COL_PING3      = '86'  # ping3
COL_PING4      = '87'  # ping4


# Set to an integer to limit files processed (useful for testing)
# Set to None to process all files
MAX_FILES = None

STAGE_DIR.mkdir(parents=True, exist_ok=True)
os.makedirs(TMP_DIR, exist_ok=True)

print(f"RAW_DIR:   {RAW_DIR}")
print(f"STAGE_DIR: {STAGE_DIR}")
print(f"TMP_DIR:   {TMP_DIR}")
print(f"MAX_FILES: {MAX_FILES}")

RAW_DIR:   /home/jovyan/data/sim/raw/sim_test_decoded/2025
STAGE_DIR: /home/jovyan/data/stage/handover_events
TMP_DIR:   /tmp/duckdb_tmp
MAX_FILES: None

In [8]:
## Connect DuckDB

import os, psutil

TOTAL_RAM_GB = round(psutil.virtual_memory().total / (1024**3), 1)
DUCKDB_THREADS = max(1, min(4, os.cpu_count() or 4))
# Use 75% of available RAM â€” safe headroom for OS + Jupyter kernel overhead
DUCKDB_MEM_GB = max(4, int(TOTAL_RAM_GB * 0.75))

con = duckdb.connect()  # in-memory â€” staging doesn't need persistence
con.execute(f"SET temp_directory='{TMP_DIR}'")
con.execute(f"SET memory_limit='{DUCKDB_MEM_GB}GB'")
con.execute(f"SET threads={DUCKDB_THREADS}")
con.execute("SET preserve_insertion_order=false")

print(f"CPUs: {os.cpu_count()}")
print(f"RAM:  {TOTAL_RAM_GB} GB")
print(f"DuckDB memory_limit: {DUCKDB_MEM_GB}GB")
print(f"DuckDB threads: {DUCKDB_THREADS}")

CPUs: 4
RAM:  23.5 GB
DuckDB memory_limit: 17GB
DuckDB threads: 4

In [9]:
## Find raw files

exts = {".gz", ".csv", ".txt"}
all_files = sorted([
    p for p in RAW_DIR.rglob("*")
    if p.is_file() and p.suffix.lower() in exts
])

raw_files = all_files[:MAX_FILES] if MAX_FILES else all_files

print(f"Total files found: {len(all_files)}")
print(f"Files to consider: {len(raw_files)}")

Total files found: 364
Files to consider: 364

In [10]:
## Process files â€” resumable, DuckDB native

skipped = 0
processed = 0
total_good = 0
total_bad = 0
run_start = time.time()

for i, path in enumerate(raw_files, 1):

    # Derive the expected output path from the filename date
    # e.g. 2025_06_15.txt -> event_date=2025-06-15
    stem = path.stem  # e.g. '2025_06_15'
    event_date = stem.replace('_', '-')  # e.g. '2025-06-15'
    out_dir  = STAGE_DIR / f"event_date={event_date}"
    out_file = out_dir / "stage.parquet"

    # --- Resumable: skip if already staged ---
    if out_file.exists():
        skipped += 1
        print(f"[{i}/{len(raw_files)}] SKIP {path.name}")
        continue

    file_start = time.time()

    try:
        out_dir.mkdir(parents=True, exist_ok=True)

        # DuckDB reads the CSV and writes parquet in one shot
        # column0..columnN maps to zero-based column positions
        result = con.execute(f"""
            COPY (
                SELECT
                    column{COL_VEHICLE_ID}  AS vehicle_id,
                    column{COL_IMSI}        AS imsi,
                    column{COL_EVENT_TS}    AS event_ts,
                    column{COL_CELL_ID}     AS cell_id,
                    column{COL_RAT}         AS rat,
                    '{path.name}'           AS source_file,
                    TRY_CAST(column{COL_PCI1_RSRP} AS DOUBLE) AS pci_1_rsrp,
                    TRY_CAST(column{COL_PCI1_RSRQ} AS DOUBLE) AS pci_1_rsrq,
                    TRY_CAST(column{COL_PING1}     AS DOUBLE) AS ping1,
                    TRY_CAST(column{COL_PING2}     AS DOUBLE) AS ping2,
                    TRY_CAST(column{COL_PING3}     AS DOUBLE) AS ping3,
                    TRY_CAST(column{COL_PING4}     AS DOUBLE) AS ping4
                FROM read_csv(
                    '{path}',
                    header        = false,
                    ignore_errors = true,
                    compression   = 'auto',
                    delim         = ','
                )
                WHERE column{COL_VEHICLE_ID} IS NOT NULL
                  AND column{COL_CELL_ID}    IS NOT NULL
                  AND column{COL_EVENT_TS}   IS NOT NULL
            ) TO '{out_file}' (FORMAT PARQUET)
        """)

        elapsed = time.time() - file_start
        # Count rows written
        n_rows = con.execute(f"SELECT COUNT(*) FROM read_parquet('{out_file}')").fetchone()[0]
        total_good += n_rows
        processed += 1
        pct = 100.0 * i / len(raw_files)
        run_elapsed = time.time() - run_start
        rate = processed / run_elapsed  # files/sec
        remaining = len(raw_files) - i
        eta_s = remaining / rate if rate > 0 else 0
        _h, _rem = divmod(int(eta_s), 3600); _m, _s = divmod(_rem, 60)
        eta_str = f"{_h}h{_m:02d}m" if _h > 0 else f"{_m}m{_s:02d}s"
        print(
            f"[{i}/{len(raw_files)}] {path.name} → {n_rows:,} rows "
            f"({elapsed:.1f}s) | {pct:.0f}% | ETA {eta_str}",
            flush=True,
        )
        with open("/tmp/stage_progress.json", "w") as _pf:
            json.dump({
                "processed": processed, "skipped": skipped, "errors": total_bad,
                "total_files": len(raw_files), "pct_done": round(pct, 1),
                "total_rows": total_good,
                "elapsed_min": round(run_elapsed / 60, 1),
                "eta_min": round(eta_s / 60, 1),
                "last_file": path.name,
                "updated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
            }, _pf, indent=2)

    except Exception as e:
        total_bad += 1
        print(f"[{i}/{len(raw_files)}] ERROR {path.name}: {e}")

total_elapsed = time.time() - run_start
print(f"\nDone. {processed} processed, {skipped} skipped, {total_bad} errors")
print(f"Total rows staged: {total_good:,}")
print(f"Total runtime: {total_elapsed/60:.1f} min")

[1/364] SKIP 2025_01_01.gz
[2/364] SKIP 2025_01_02.gz
[3/364] SKIP 2025_01_03.gz
[4/364] SKIP 2025_01_04.gz
[5/364] SKIP 2025_01_05.gz
[6/364] SKIP 2025_01_06.gz
[7/364] SKIP 2025_01_07.gz
[8/364] SKIP 2025_01_08.gz
[9/364] SKIP 2025_01_09.gz
[10/364] SKIP 2025_01_10.gz
[11/364] SKIP 2025_01_11.gz
[12/364] SKIP 2025_01_12.gz
[13/364] SKIP 2025_01_13.gz
[14/364] SKIP 2025_01_14.gz
[15/364] SKIP 2025_01_15.gz
[16/364] SKIP 2025_01_17.gz
[17/364] SKIP 2025_01_18.gz
[18/364] SKIP 2025_01_19.gz
[19/364] SKIP 2025_01_20.gz
[20/364] SKIP 2025_01_21.gz
[21/364] SKIP 2025_01_22.gz
[22/364] SKIP 2025_01_23.gz
[23/364] SKIP 2025_01_24.gz
[24/364] SKIP 2025_01_25.gz
[25/364] SKIP 2025_01_26.gz
[26/364] SKIP 2025_01_27.gz
[27/364] SKIP 2025_01_28.gz
[28/364] SKIP 2025_01_29.gz
[29/364] SKIP 2025_01_30.gz
[30/364] SKIP 2025_01_31.gz
[31/364] SKIP 2025_02_01.gz
[32/364] SKIP 2025_02_02.gz
[33/364] SKIP 2025_02_03.gz
[34/364] SKIP 2025_02_04.gz
[35/364] SKIP 2025_02_05.gz
[36/364] SKIP 2025_02_06.gz
[37/364] SKIP 2025_02_07.gz
[38/364] SKIP 2025_02_08.gz
[39/364] SKIP 2025_02_09.gz
[40/364] SKIP 2025_02_10.gz
[41/364] SKIP 2025_02_11.gz
[42/364] SKIP 2025_02_12.gz
[43/364] SKIP 2025_02_13.gz
[44/364] SKIP 2025_02_14.gz
[45/364] SKIP 2025_02_15.gz
[46/364] SKIP 2025_02_16.gz
[47/364] SKIP 2025_02_17.gz
[48/364] SKIP 2025_02_18.gz
[49/364] SKIP 2025_02_19.gz
[50/364] SKIP 2025_02_20.gz
[51/364] SKIP 2025_02_21.gz
[52/364] SKIP 2025_02_22.gz
[53/364] SKIP 2025_02_23.gz
[54/364] SKIP 2025_02_24.gz
[55/364] SKIP 2025_02_25.gz
[56/364] SKIP 2025_02_26.gz
[57/364] SKIP 2025_02_27.gz
[58/364] SKIP 2025_02_28.gz
[59/364] SKIP 2025_03_01.gz
[60/364] SKIP 2025_03_02.gz
[61/364] SKIP 2025_03_03.gz
[62/364] SKIP 2025_03_04.gz
[63/364] SKIP 2025_03_05.gz
[64/364] SKIP 2025_03_06.gz
[65/364] SKIP 2025_03_07.gz
[66/364] SKIP 2025_03_08.gz
[67/364] SKIP 2025_03_09.gz
[68/364] SKIP 2025_03_10.gz
[69/364] SKIP 2025_03_11.gz
[70/364] SKIP 2025_03_12.gz
[71/364] SKIP 2025_03_13.gz
[72/364] SKIP 2025_03_14.gz
[73/364] SKIP 2025_03_15.gz
[74/364] SKIP 2025_03_16.gz
[75/364] SKIP 2025_03_17.gz
[76/364] SKIP 2025_03_18.gz
[77/364] SKIP 2025_03_19.gz
[78/364] SKIP 2025_03_20.gz
[79/364] SKIP 2025_03_21.gz
[80/364] SKIP 2025_03_22.gz
[81/364] SKIP 2025_03_23.gz
[82/364] SKIP 2025_03_24.gz
[83/364] SKIP 2025_03_25.gz
[84/364] SKIP 2025_03_26.gz
[85/364] SKIP 2025_03_27.gz
[86/364] SKIP 2025_03_28.gz
[87/364] SKIP 2025_03_29.gz
[88/364] SKIP 2025_03_30.gz
[89/364] SKIP 2025_03_31.gz
[90/364] SKIP 2025_04_01.gz
[91/364] SKIP 2025_04_02.gz
[92/364] SKIP 2025_04_03.gz
[93/364] SKIP 2025_04_04.gz
[94/364] SKIP 2025_04_05.gz
[95/364] SKIP 2025_04_06.gz
[96/364] SKIP 2025_04_07.gz
[97/364] SKIP 2025_04_08.gz
[98/364] SKIP 2025_04_09.gz
[99/364] SKIP 2025_04_10.gz
[100/364] SKIP 2025_04_11.gz
[101/364] SKIP 2025_04_12.gz
[102/364] SKIP 2025_04_13.gz
[103/364] SKIP 2025_04_14.gz
[104/364] SKIP 2025_04_15.gz
[105/364] SKIP 2025_04_16.gz
[106/364] SKIP 2025_04_17.gz
[107/364] SKIP 2025_04_18.gz
[108/364] SKIP 2025_04_19.gz
[109/364] SKIP 2025_04_20.gz
[110/364] SKIP 2025_04_21.gz
[111/364] SKIP 2025_04_22.gz
[112/364] SKIP 2025_04_23.gz
[113/364] SKIP 2025_04_24.gz
[114/364] SKIP 2025_04_25.gz
[115/364] SKIP 2025_04_26.gz
[116/364] SKIP 2025_04_27.gz
[117/364] SKIP 2025_04_28.gz
[118/364] SKIP 2025_04_29.gz
[119/364] SKIP 2025_04_30.gz
[120/364] SKIP 2025_05_01.gz
[121/364] SKIP 2025_05_02.gz
[122/364] SKIP 2025_05_03.gz
[123/364] SKIP 2025_05_04.gz
[124/364] SKIP 2025_05_05.gz
[125/364] SKIP 2025_05_06.gz
[126/364] SKIP 2025_05_07.gz
[127/364] SKIP 2025_05_08.gz
[128/364] SKIP 2025_05_09.gz
[129/364] SKIP 2025_05_10.gz
[130/364] SKIP 2025_05_11.gz
[131/364] SKIP 2025_05_12.gz
[132/364] SKIP 2025_05_13.gz
[133/364] SKIP 2025_05_14.gz
[134/364] SKIP 2025_05_15.gz
[135/364] SKIP 2025_05_16.gz
[136/364] SKIP 2025_05_17.gz
[137/364] SKIP 2025_05_18.gz
[138/364] SKIP 2025_05_19.gz
[139/364] SKIP 2025_05_20.gz
[140/364] SKIP 2025_05_21.gz
[141/364] SKIP 2025_05_22.gz
[142/364] SKIP 2025_05_23.gz
[143/364] SKIP 2025_05_24.gz
[144/364] SKIP 2025_05_25.gz
[145/364] SKIP 2025_05_26.gz
[146/364] SKIP 2025_05_27.gz
[147/364] SKIP 2025_05_28.gz
[148/364] SKIP 2025_05_29.gz
[149/364] SKIP 2025_05_30.gz
[150/364] SKIP 2025_05_31.gz
[151/364] SKIP 2025_06_01.gz
[152/364] SKIP 2025_06_02.gz
[153/364] SKIP 2025_06_03.gz
[154/364] SKIP 2025_06_04.gz
[155/364] SKIP 2025_06_05.gz
[156/364] SKIP 2025_06_06.gz
[157/364] SKIP 2025_06_07.gz
[158/364] SKIP 2025_06_08.gz
[159/364] SKIP 2025_06_09.gz
[160/364] SKIP 2025_06_10.gz
[161/364] SKIP 2025_06_11.gz
[162/364] SKIP 2025_06_12.gz
[163/364] SKIP 2025_06_13.gz
[164/364] SKIP 2025_06_14.gz
[165/364] SKIP 2025_06_15.gz
[166/364] SKIP 2025_06_16.gz
[167/364] SKIP 2025_06_17.gz
[168/364] SKIP 2025_06_18.gz
[169/364] SKIP 2025_06_19.gz
[170/364] SKIP 2025_06_20.gz
[171/364] SKIP 2025_06_21.gz
[172/364] SKIP 2025_06_22.gz
[173/364] SKIP 2025_06_23.gz
[174/364] SKIP 2025_06_24.gz
[175/364] SKIP 2025_06_25.gz
[176/364] SKIP 2025_06_26.gz
[177/364] SKIP 2025_06_27.gz
[178/364] SKIP 2025_06_28.gz
[179/364] SKIP 2025_06_29.gz
[180/364] SKIP 2025_06_30.gz
[181/364] SKIP 2025_07_01.gz
[182/364] SKIP 2025_07_02.gz
[183/364] SKIP 2025_07_03.gz
[184/364] SKIP 2025_07_04.gz
[185/364] SKIP 2025_07_05.gz
[186/364] SKIP 2025_07_06.gz
[187/364] SKIP 2025_07_07.gz
[188/364] SKIP 2025_07_08.gz
[189/364] SKIP 2025_07_09.gz
[190/364] SKIP 2025_07_10.gz
[191/364] SKIP 2025_07_11.gz
[192/364] SKIP 2025_07_12.gz
[193/364] SKIP 2025_07_13.gz
[194/364] SKIP 2025_07_14.gz
[195/364] SKIP 2025_07_15.gz
[196/364] SKIP 2025_07_16.gz
[197/364] SKIP 2025_07_17.gz
[198/364] SKIP 2025_07_18.gz
[199/364] SKIP 2025_07_19.gz
[200/364] SKIP 2025_07_20.gz
[201/364] SKIP 2025_07_21.gz
[202/364] SKIP 2025_07_22.gz
[203/364] SKIP 2025_07_23.gz
[204/364] SKIP 2025_07_24.gz
[205/364] SKIP 2025_07_25.gz
[206/364] SKIP 2025_07_26.gz
[207/364] SKIP 2025_07_27.gz
[208/364] SKIP 2025_07_28.gz
[209/364] SKIP 2025_07_29.gz
[210/364] SKIP 2025_07_30.gz
[211/364] SKIP 2025_07_31.gz
[212/364] SKIP 2025_08_01.gz
[213/364] SKIP 2025_08_02.gz
[214/364] SKIP 2025_08_03.gz
[215/364] SKIP 2025_08_04.gz
[216/364] SKIP 2025_08_05.gz
[217/364] SKIP 2025_08_06.gz
[218/364] SKIP 2025_08_07.gz
[219/364] SKIP 2025_08_08.gz
[220/364] SKIP 2025_08_09.gz
[221/364] SKIP 2025_08_10.gz
[222/364] SKIP 2025_08_11.gz
[223/364] SKIP 2025_08_12.gz
[224/364] SKIP 2025_08_13.gz
[225/364] SKIP 2025_08_14.gz
[226/364] SKIP 2025_08_15.gz
[227/364] SKIP 2025_08_16.gz
[228/364] SKIP 2025_08_17.gz
[229/364] SKIP 2025_08_18.gz
[230/364] SKIP 2025_08_19.gz
[231/364] SKIP 2025_08_20.gz
[232/364] SKIP 2025_08_21.gz
[233/364] SKIP 2025_08_22.gz
[234/364] SKIP 2025_08_23.gz
[235/364] SKIP 2025_08_24.gz
[236/364] SKIP 2025_08_25.gz
[237/364] SKIP 2025_08_26.gz
[238/364] SKIP 2025_08_27.gz
[239/364] SKIP 2025_08_28.gz
[240/364] SKIP 2025_08_29.gz
[241/364] SKIP 2025_08_30.gz
[242/364] SKIP 2025_08_31.gz
[243/364] SKIP 2025_09_01.gz
[244/364] SKIP 2025_09_02.gz
[245/364] SKIP 2025_09_03.gz
[246/364] SKIP 2025_09_04.gz
[247/364] SKIP 2025_09_05.gz
[248/364] SKIP 2025_09_06.gz
[249/364] SKIP 2025_09_07.gz
[250/364] SKIP 2025_09_08.gz
[251/364] SKIP 2025_09_09.gz
[252/364] SKIP 2025_09_10.gz
[253/364] SKIP 2025_09_11.gz
[254/364] SKIP 2025_09_12.gz
[255/364] SKIP 2025_09_13.gz
[256/364] SKIP 2025_09_14.gz
[257/364] SKIP 2025_09_15.gz
[258/364] SKIP 2025_09_16.gz
[259/364] SKIP 2025_09_17.gz
[260/364] SKIP 2025_09_18.gz
[261/364] SKIP 2025_09_19.gz
[262/364] SKIP 2025_09_20.gz
[263/364] SKIP 2025_09_21.gz
[264/364] SKIP 2025_09_22.gz
[265/364] SKIP 2025_09_23.gz
[266/364] SKIP 2025_09_24.gz
[267/364] SKIP 2025_09_25.gz
[268/364] SKIP 2025_09_26.gz
[269/364] SKIP 2025_09_27.gz
[270/364] SKIP 2025_09_28.gz
[271/364] SKIP 2025_09_29.gz
[272/364] SKIP 2025_09_30.gz
[273/364] SKIP 2025_10_01.gz
[274/364] SKIP 2025_10_02.gz
[275/364] SKIP 2025_10_03.gz
[276/364] SKIP 2025_10_04.gz
[277/364] SKIP 2025_10_05.gz
[278/364] SKIP 2025_10_06.gz
[279/364] SKIP 2025_10_07.gz
[280/364] SKIP 2025_10_08.gz
[281/364] SKIP 2025_10_09.gz
[282/364] SKIP 2025_10_10.gz
[283/364] SKIP 2025_10_11.gz
[284/364] SKIP 2025_10_12.gz
[285/364] SKIP 2025_10_13.gz
[286/364] SKIP 2025_10_14.gz
[287/364] SKIP 2025_10_15.gz
[288/364] SKIP 2025_10_16.gz
[289/364] SKIP 2025_10_17.gz
[290/364] SKIP 2025_10_18.gz
[291/364] SKIP 2025_10_19.gz
[292/364] SKIP 2025_10_20.gz
[293/364] SKIP 2025_10_21.gz
[294/364] SKIP 2025_10_22.gz
[295/364] SKIP 2025_10_23.gz
[296/364] SKIP 2025_10_24.gz
[297/364] SKIP 2025_10_25.gz
[298/364] SKIP 2025_10_26.gz
[299/364] SKIP 2025_10_27.gz
[300/364] SKIP 2025_10_28.gz
[301/364] SKIP 2025_10_29.gz
[302/364] SKIP 2025_10_30.gz
[303/364] SKIP 2025_10_31.gz
[304/364] SKIP 2025_11_01.gz
[305/364] SKIP 2025_11_02.gz
[306/364] SKIP 2025_11_03.gz
[307/364] SKIP 2025_11_04.gz
[308/364] SKIP 2025_11_05.gz
[309/364] SKIP 2025_11_06.gz
[310/364] SKIP 2025_11_07.gz
[311/364] SKIP 2025_11_08.gz
[312/364] SKIP 2025_11_09.gz
[313/364] SKIP 2025_11_10.gz
[314/364] SKIP 2025_11_11.gz
[315/364] SKIP 2025_11_12.gz
[316/364] SKIP 2025_11_13.gz
[317/364] SKIP 2025_11_14.gz
[318/364] SKIP 2025_11_15.gz
[319/364] SKIP 2025_11_16.gz
[320/364] SKIP 2025_11_17.gz
[321/364] SKIP 2025_11_18.gz
[322/364] SKIP 2025_11_19.gz
[323/364] SKIP 2025_11_20.gz
[324/364] SKIP 2025_11_21.gz
[325/364] SKIP 2025_11_22.gz
[326/364] SKIP 2025_11_23.gz
[327/364] SKIP 2025_11_24.gz
[328/364] SKIP 2025_11_25.gz
[329/364] SKIP 2025_11_26.gz
[330/364] SKIP 2025_11_27.gz
[331/364] SKIP 2025_11_28.gz
[332/364] SKIP 2025_11_29.gz
[333/364] SKIP 2025_11_30.gz
[334/364] SKIP 2025_12_01.gz
[335/364] SKIP 2025_12_02.gz
[336/364] SKIP 2025_12_03.gz
[337/364] SKIP 2025_12_04.gz
[338/364] SKIP 2025_12_05.gz
[339/364] SKIP 2025_12_06.gz
[340/364] SKIP 2025_12_07.gz
[341/364] SKIP 2025_12_08.gz
[342/364] SKIP 2025_12_09.gz
[343/364] SKIP 2025_12_10.gz
[344/364] SKIP 2025_12_11.gz
[345/364] SKIP 2025_12_12.gz
[346/364] SKIP 2025_12_13.gz
[347/364] SKIP 2025_12_14.gz
[348/364] SKIP 2025_12_15.gz
[349/364] SKIP 2025_12_16.gz
[350/364] SKIP 2025_12_17.gz
[351/364] SKIP 2025_12_18.gz
[352/364] SKIP 2025_12_19.gz
[353/364] SKIP 2025_12_20.gz
[354/364] SKIP 2025_12_21.gz
[355/364] SKIP 2025_12_22.gz
[356/364] SKIP 2025_12_23.gz
[357/364] SKIP 2025_12_24.gz
[358/364] SKIP 2025_12_25.gz
[359/364] SKIP 2025_12_26.gz
[360/364] SKIP 2025_12_27.gz
[361/364] SKIP 2025_12_28.gz
[362/364] SKIP 2025_12_29.gz
[363/364] SKIP 2025_12_30.gz
[364/364] SKIP 2025_12_31.gz

Done. 0 processed, 364 skipped, 0 errors
Total rows staged: 0
Total runtime: 0.0 min

In [11]:
## Verify â€” check a sample parquet file

sample_files = list(STAGE_DIR.rglob("*.parquet"))
print(f"Parquet files on disk: {len(sample_files)}")

con.execute(f"""
    SELECT *
    FROM read_parquet('{sample_files[0]}')
    LIMIT 3
""").df()

Parquet files on disk: 478

,vehicle_id,imsi,event_ts,cell_id,rat,source_file,event_date
0,F140A413CDBACB245F79DAE1D7438EC4,000000000000000,2025-01-01 00:02:01.793,69492489,4G,2025_01_01.gz,2025-01-01
1,F140A413CDBACB245F79DAE1D7438EC4,000000000000000,2025-01-01 00:10:05.626,69492489,4G,2025_01_01.gz,2025-01-01
2,F140A413CDBACB245F79DAE1D7438EC4,000000000000000,2025-01-01 00:18:09.436,69492708,4G,2025_01_01.gz,2025-01-01

In [ ]:
## Register handover_events in analytics DuckDB

import os
import psutil

# Set to True to force a full table rebuild even if it already exists.
FORCE_REBUILD = False

# DuckDB in this environment runs on CPU threads.
# GPU acceleration is not available in this notebook path.
USE_GPU = False

# Free memory from both connections
for _conn in ('con', 'analytics'):
    try:
        globals()[_conn].close()
    except Exception:
        pass

ANALYTICS_DB = "/home/jovyan/data/analytics.duckdb"

# Increase parallelism for faster initial rebuilds, capped to stay stable in container.
ANALYTICS_THREADS = max(2, min(8, os.cpu_count() or 4))

# Use currently available RAM (not total RAM) to avoid OOM in constrained containers.
available_gb = max(1, int(psutil.virtual_memory().available / (1024**3)))
ANALYTICS_MEM_GB = max(2, min(12, int(available_gb * 0.70)))


def connect_analytics(mem_gb: int):
    return duckdb.connect(
        ANALYTICS_DB,
        config={
            "temp_directory": TMP_DIR,
            "memory_limit": f"{mem_gb}GB",
            "threads": str(ANALYTICS_THREADS),
            "preserve_insertion_order": "false",
            "enable_progress_bar": "true",
        },
    )


try:
    analytics = connect_analytics(ANALYTICS_MEM_GB)
except Exception as e:
    retry_mem_gb = max(1, ANALYTICS_MEM_GB // 2)
    print(f"Connect failed at {ANALYTICS_MEM_GB}GB ({e}); retrying at {retry_mem_gb}GB...")
    analytics = connect_analytics(retry_mem_gb)
    ANALYTICS_MEM_GB = retry_mem_gb

print(f"Analytics DB: {ANALYTICS_DB}")
print(f"Available RAM now: {available_gb}GB")
print(f"Analytics memory_limit: {ANALYTICS_MEM_GB}GB")
print(f"Analytics threads: {ANALYTICS_THREADS}")
print(f"GPU enabled: {USE_GPU} (DuckDB path here is CPU-only)")

# --- Resumable: skip rebuild if table already exists and FORCE_REBUILD is False ---
_table_exists = analytics.execute(
    "SELECT COUNT(*) FROM information_schema.tables "
    "WHERE table_name = 'handover_events'"
).fetchone()[0] > 0

if _table_exists and not FORCE_REBUILD:
    print("handover_events already exists â€” skipping rebuild (set FORCE_REBUILD=True to override).")
else:
    day_dirs = sorted([p for p in STAGE_DIR.glob("event_date=*") if p.is_dir()])
    if not day_dirs:
        raise FileNotFoundError(f"No staged day partitions found under {STAGE_DIR}")

    if FORCE_REBUILD:
        print("FORCE_REBUILD=True â€” dropping and rebuilding handover_events...")
    else:
        print("handover_events not found â€” building for the first time...")

    analytics.execute("DROP TABLE IF EXISTS handover_events")
    build_start = time.time()
    total_days = len(day_dirs)
    print(f"Building from {total_days} daily partitions...")

    for idx, day_dir in enumerate(day_dirs, start=1):
        day_glob = str(day_dir / "*.parquet")
        day_name = day_dir.name.replace("event_date=", "")

        day_select = f"""
            SELECT
                vehicle_id,
                imsi,
                event_ts,
                cell_id,
                rat,
                source_file,
                CAST(event_ts AS DATE) AS event_date
            FROM read_parquet('{day_glob}')
            WHERE vehicle_id IS NOT NULL
              AND cell_id    IS NOT NULL
              AND event_ts   IS NOT NULL
        """

        if idx == 1:
            analytics.execute(f"CREATE TABLE handover_events AS {day_select}")
        else:
            analytics.execute(f"INSERT INTO handover_events {day_select}")

        if idx == 1 or idx % 10 == 0 or idx == total_days:
            elapsed_min = (time.time() - build_start) / 60
            print(f"[{idx}/{total_days}] loaded {day_name} | elapsed {elapsed_min:.1f} min")

    print(f"Build complete in {(time.time() - build_start)/60:.1f} min")

try:
    summary = analytics.execute("""
        SELECT
            COUNT(*)                                AS total_rows,
            APPROX_COUNT_DISTINCT(vehicle_id)       AS approx_vehicles,
            APPROX_COUNT_DISTINCT(cell_id)          AS approx_cells,
            MIN(event_ts)                           AS min_event,
            MAX(event_ts)                           AS max_event
        FROM handover_events
    """).df()
except duckdb.OutOfMemoryException:
    print("Summary query hit OOM; returning lightweight stats instead.")
    summary = analytics.execute("""
        SELECT
            COUNT(*)      AS total_rows,
            MIN(event_ts) AS min_event,
            MAX(event_ts) AS max_event
        FROM handover_events
    """).df()
summary

Analytics DB: /home/jovyan/data/analytics.duckdb
Available RAM now: 20GB
Analytics memory_limit: 8GB
Analytics threads: 1
handover_events not found â€” building for the first time...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,total_rows,approx_vehicles,approx_cells,min_event,max_event
0,1735661691,87876,1197011,2025-01-01 00:02:01.793,2025-12-31 23:59:56.589