# Trip Extraction — Day-by-Day DuckDB

Processes one day at a time to keep memory footprint small and constant.
Skips dates that already have parquet output (resumable).

## Trip logic
- Poll interval: ~450 seconds
- **Cell handover** (cell_id changes between consecutive polls) = vehicle moving
- **Stationary** = same cell for >= `STATIONARY_POLLS` consecutive polls
- **Trip** = continuous run of handovers between two stationary periods

```
polls:  [C1] [C2] [C3] [C3] [C3] [C4] [C5] [C5] [C5]
        move move move same same move move same same
        |------ TRIP 1 ------|  park  |--- TRIP 2 ---|
```

In [1]:
## Config

import duckdb
import os
from pathlib import Path

DB_PATH   = "/home/jovyan/data/analytics.duckdb"
STAGE_DIR = Path("/home/jovyan/data/stage/trips")
TMP_DIR   = "/home/jovyan/data/tmp"

# How many consecutive same-cell polls = stationary
STATIONARY_POLLS = 2      # 2 x 450s = 15 min

# Minimum cell handovers for a trip to be kept
MIN_HANDOVERS = 2

# Minimum distinct cells visited — filters cell-edge oscillation
MIN_CELLS = 3

MAX_FILES = 30

STAGE_DIR.mkdir(parents=True, exist_ok=True)
os.makedirs(TMP_DIR, exist_ok=True)

print(f"STATIONARY_POLLS={STATIONARY_POLLS}, MIN_HANDOVERS={MIN_HANDOVERS}, MIN_CELLS={MIN_CELLS}")

STATIONARY_POLLS=2, MIN_HANDOVERS=2, MIN_CELLS=3

In [2]:
## Connect and configure DuckDB

con = duckdb.connect(DB_PATH)
con.execute(f"SET memory_limit='8GB'")
con.execute(f"SET temp_directory='{TMP_DIR}'")
con.execute("SET preserve_insertion_order=false")
con.execute("SET threads=4")

## Rebuild handover_events from parquet
#con.execute("DROP TABLE IF EXISTS handover_events")
#con.execute("""
#    CREATE TABLE handover_events AS
#    SELECT *
#    FROM read_parquet('/home/jovyan/data/stage/handover_events/**/*.parquet')
#""")

summary = con.execute("""
    SELECT
        COUNT(*)                   AS total_rows,
        COUNT(DISTINCT vehicle_id) AS vehicles,
        MIN(event_date)            AS first_date,
        MAX(event_date)            AS last_date,
        COUNT(DISTINCT event_date) AS n_dates
    FROM handover_events
""").df()
print(summary.to_string(index=False))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

 total_rows  vehicles first_date  last_date  n_dates
  913539144     99610 2025-01-01 2025-11-01      304

In [3]:
## Get list of dates to process

dates = [
    row[0] for row in
    con.execute("SELECT DISTINCT event_date FROM handover_events ORDER BY event_date").fetchall()
]

print(f"Dates to process: {len(dates)}")
print(f"  First: {dates[0]}")
print(f"  Last:  {dates[-1]}")

Dates to process: 304
  First: 2025-01-01
  Last:  2025-11-01

In [4]:
## Process one day at a time

import time

total_trips = 0
skipped = 0
run_start = time.time()

for i, event_date in enumerate(dates, 1):

    # --- Resumable: skip if parquet already written for this date ---
    out_dir = STAGE_DIR / f"event_date={event_date}"
    if out_dir.exists() and any(out_dir.glob("*.parquet")):
        skipped += 1
        print(f"[{i}/{len(dates)}] SKIP {event_date} (already done)")
        continue

    day_start = time.time()

    # --- Step A: build trips_raw for this date only ---
    con.execute("DROP TABLE IF EXISTS trips_raw")
    con.execute(f"""
    CREATE TABLE trips_raw AS
    WITH
    ranked AS (
        SELECT
            vehicle_id, imsi, event_ts, cell_id, rat, event_date,
            LAG(cell_id) OVER (PARTITION BY vehicle_id ORDER BY event_ts) AS prev_cell,
            CASE
                WHEN cell_id != LAG(cell_id) OVER (PARTITION BY vehicle_id ORDER BY event_ts)
                  OR LAG(cell_id) OVER (PARTITION BY vehicle_id ORDER BY event_ts) IS NULL
                THEN 1 ELSE 0
            END AS cell_changed
        FROM handover_events
        WHERE event_date = '{event_date}'
    ),
    with_run AS (
        SELECT *,
            SUM(cell_changed) OVER (PARTITION BY vehicle_id ORDER BY event_ts) AS cell_run_id
        FROM ranked
    ),
    with_poll_count AS (
        SELECT *,
            ROW_NUMBER() OVER (PARTITION BY vehicle_id, cell_run_id ORDER BY event_ts) AS same_cell_poll_count
        FROM with_run
    ),
    with_stationary AS (
        SELECT *,
            same_cell_poll_count >= {STATIONARY_POLLS} AS stationary,
            LAG(same_cell_poll_count >= {STATIONARY_POLLS})
                OVER (PARTITION BY vehicle_id ORDER BY event_ts) AS prev_stationary
        FROM with_poll_count
    ),
    with_trip_flags AS (
        SELECT *,
            CASE
                WHEN cell_changed = 1
                 AND (prev_stationary OR prev_stationary IS NULL)
                THEN 1 ELSE 0
            END AS trip_start_flag
        FROM with_stationary
    ),
    with_trip_seq AS (
        SELECT *,
            SUM(trip_start_flag) OVER (PARTITION BY vehicle_id ORDER BY event_ts) AS trip_seq,
            NOT stationary AS in_trip
        FROM with_trip_flags
    )
    SELECT *,
        CASE WHEN NOT stationary
            THEN vehicle_id || '_trip_' || LPAD(CAST(trip_seq AS VARCHAR), 3, '0')
            ELSE NULL
        END AS trip_id
    FROM with_trip_seq
    """)

    # --- Step B: aggregate trip summaries ---
    con.execute("DROP TABLE IF EXISTS trip_agg")
    con.execute("""
    CREATE TABLE trip_agg AS
    SELECT
        vehicle_id, imsi, trip_id, trip_seq, event_date,
        MIN(event_ts)                                      AS trip_start,
        MAX(event_ts)                                      AS trip_end,
        COUNT(*)                                           AS n_events,
        COUNT(DISTINCT cell_id)                            AS n_cells,
        SUM(CASE WHEN cell_changed = 1 THEN 1 ELSE 0 END) AS n_handovers,
        FIRST(cell_id ORDER BY event_ts)                   AS first_cell,
        LAST(cell_id ORDER BY event_ts)                    AS last_cell,
        MODE(rat)                                          AS dominant_rat
    FROM trips_raw
    WHERE in_trip
    GROUP BY vehicle_id, imsi, trip_id, trip_seq, event_date
    """)

    # --- Step C: free trips_raw, build cell sequences ---
    con.execute("DROP TABLE IF EXISTS trips_raw")

    con.execute("DROP TABLE IF EXISTS cell_sequences")
    con.execute(f"""
    CREATE TABLE cell_sequences AS
    SELECT
        h.vehicle_id || '_trip_' || LPAD(CAST(t.trip_seq AS VARCHAR), 3, '0') AS trip_id,
        STRING_AGG(h.cell_id, ' -> ' ORDER BY h.event_ts) AS cell_sequence
    FROM handover_events h
    JOIN trip_agg t
        ON  h.vehicle_id = t.vehicle_id
        AND h.event_ts  >= t.trip_start
        AND h.event_ts  <= t.trip_end
    WHERE h.event_date = '{event_date}'
    GROUP BY 1
    """)

    # --- Step D: join and apply filters, write parquet ---
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / "trips.parquet"

    n_trips = con.execute(f"""
    COPY (
        SELECT
            a.vehicle_id, a.imsi, a.event_date, a.trip_id, a.trip_seq,
            a.trip_start, a.trip_end,
            ROUND(DATEDIFF('second', a.trip_start, a.trip_end) / 60.0, 1) AS duration_minutes,
            a.n_handovers, a.n_cells, a.n_events,
            a.first_cell, a.last_cell, a.dominant_rat,
            s.cell_sequence
        FROM trip_agg a
        LEFT JOIN cell_sequences s ON a.trip_id = s.trip_id
        WHERE a.trip_id    IS NOT NULL
          AND a.n_handovers >= {MIN_HANDOVERS}
          AND a.n_cells     >= {MIN_CELLS}
        ORDER BY vehicle_id, trip_start
    ) TO '{out_file}' (FORMAT PARQUET)
    """).fetchone()[0]

    # --- Cleanup working tables ---
    con.execute("DROP TABLE IF EXISTS trip_agg")
    con.execute("DROP TABLE IF EXISTS cell_sequences")

    total_trips += n_trips
    elapsed = time.time() - day_start
    print(f"[{i}/{len(dates)}] {event_date} → {n_trips:,} trips ({elapsed:.1f}s)")

total_elapsed = time.time() - run_start
print(f"\nDone. {len(dates) - skipped} days processed, {skipped} skipped.")
print(f"Total trips written: {total_trips:,}")
print(f"Total runtime: {total_elapsed/60:.1f} min")

[1/304] SKIP 2025-01-01 (already done)
[2/304] SKIP 2025-01-02 (already done)
[3/304] SKIP 2025-01-03 (already done)
[4/304] SKIP 2025-01-04 (already done)
[5/304] SKIP 2025-01-05 (already done)
[6/304] SKIP 2025-01-06 (already done)
[7/304] SKIP 2025-01-07 (already done)
[8/304] SKIP 2025-01-08 (already done)
[9/304] SKIP 2025-01-09 (already done)
[10/304] SKIP 2025-01-10 (already done)
[11/304] SKIP 2025-01-11 (already done)
[12/304] SKIP 2025-01-12 (already done)
[13/304] SKIP 2025-01-13 (already done)
[14/304] SKIP 2025-01-14 (already done)
[15/304] SKIP 2025-01-15 (already done)
[16/304] SKIP 2025-01-17 (already done)
[17/304] SKIP 2025-01-18 (already done)
[18/304] SKIP 2025-01-19 (already done)
[19/304] SKIP 2025-01-20 (already done)
[20/304] SKIP 2025-01-21 (already done)
[21/304] SKIP 2025-01-22 (already done)
[22/304] SKIP 2025-01-23 (already done)
[23/304] SKIP 2025-01-24 (already done)
[24/304] SKIP 2025-01-25 (already done)
[25/304] SKIP 2025-01-26 (already done)
[26/304] SKIP 2025-01-27 (already done)
[27/304] SKIP 2025-01-28 (already done)
[28/304] SKIP 2025-01-29 (already done)
[29/304] SKIP 2025-01-30 (already done)
[30/304] SKIP 2025-01-31 (already done)
[31/304] SKIP 2025-02-01 (already done)
[32/304] SKIP 2025-02-02 (already done)
[33/304] SKIP 2025-02-03 (already done)
[34/304] SKIP 2025-02-04 (already done)
[35/304] SKIP 2025-02-05 (already done)
[36/304] SKIP 2025-02-06 (already done)
[37/304] SKIP 2025-02-07 (already done)
[38/304] SKIP 2025-02-08 (already done)
[39/304] SKIP 2025-02-09 (already done)
[40/304] SKIP 2025-02-10 (already done)
[41/304] SKIP 2025-02-11 (already done)
[42/304] SKIP 2025-02-12 (already done)
[43/304] SKIP 2025-02-13 (already done)
[44/304] SKIP 2025-02-14 (already done)
[45/304] SKIP 2025-02-15 (already done)
[46/304] SKIP 2025-02-16 (already done)
[47/304] SKIP 2025-02-17 (already done)
[48/304] SKIP 2025-02-18 (already done)
[49/304] SKIP 2025-02-19 (already done)
[50/304] SKIP 2025-02-20 (already done)
[51/304] SKIP 2025-02-21 (already done)
[52/304] SKIP 2025-02-22 (already done)
[53/304] SKIP 2025-02-23 (already done)
[54/304] SKIP 2025-02-24 (already done)
[55/304] SKIP 2025-02-25 (already done)
[56/304] SKIP 2025-02-26 (already done)
[57/304] SKIP 2025-02-27 (already done)
[58/304] SKIP 2025-02-28 (already done)
[59/304] SKIP 2025-03-01 (already done)
[60/304] SKIP 2025-03-02 (already done)
[61/304] SKIP 2025-03-03 (already done)
[62/304] SKIP 2025-03-04 (already done)
[63/304] SKIP 2025-03-05 (already done)
[64/304] SKIP 2025-03-06 (already done)
[65/304] SKIP 2025-03-07 (already done)
[66/304] SKIP 2025-03-08 (already done)
[67/304] SKIP 2025-03-09 (already done)
[68/304] SKIP 2025-03-10 (already done)
[69/304] SKIP 2025-03-11 (already done)
[70/304] SKIP 2025-03-12 (already done)
[71/304] SKIP 2025-03-13 (already done)
[72/304] SKIP 2025-03-14 (already done)
[73/304] SKIP 2025-03-15 (already done)
[74/304] SKIP 2025-03-16 (already done)
[75/304] SKIP 2025-03-17 (already done)
[76/304] SKIP 2025-03-18 (already done)
[77/304] SKIP 2025-03-19 (already done)
[78/304] SKIP 2025-03-20 (already done)
[79/304] SKIP 2025-03-21 (already done)
[80/304] SKIP 2025-03-22 (already done)
[81/304] SKIP 2025-03-23 (already done)
[82/304] SKIP 2025-03-24 (already done)
[83/304] SKIP 2025-03-25 (already done)
[84/304] SKIP 2025-03-26 (already done)
[85/304] SKIP 2025-03-27 (already done)
[86/304] SKIP 2025-03-28 (already done)
[87/304] SKIP 2025-03-29 (already done)
[88/304] SKIP 2025-03-30 (already done)
[89/304] SKIP 2025-03-31 (already done)
[90/304] SKIP 2025-04-01 (already done)
[91/304] SKIP 2025-04-02 (already done)
[92/304] SKIP 2025-04-03 (already done)
[93/304] SKIP 2025-04-04 (already done)
[94/304] SKIP 2025-04-05 (already done)
[95/304] SKIP 2025-04-06 (already done)
[96/304] SKIP 2025-04-07 (already done)
[97/304] SKIP 2025-04-08 (already done)
[98/304] SKIP 2025-04-09 (already done)
[99/304] SKIP 2025-04-10 (already done)
[100/304] SKIP 2025-04-11 (already done)
[101/304] SKIP 2025-04-12 (already done)
[102/304] SKIP 2025-04-13 (already done)
[103/304] SKIP 2025-04-14 (already done)
[104/304] SKIP 2025-04-15 (already done)
[105/304] SKIP 2025-04-16 (already done)
[106/304] SKIP 2025-04-17 (already done)
[107/304] SKIP 2025-04-18 (already done)
[108/304] SKIP 2025-04-19 (already done)
[109/304] SKIP 2025-04-20 (already done)
[110/304] SKIP 2025-04-21 (already done)
[111/304] SKIP 2025-04-22 (already done)
[112/304] SKIP 2025-04-23 (already done)
[113/304] SKIP 2025-04-24 (already done)
[114/304] SKIP 2025-04-25 (already done)
[115/304] SKIP 2025-04-26 (already done)
[116/304] SKIP 2025-04-27 (already done)
[117/304] SKIP 2025-04-28 (already done)
[118/304] SKIP 2025-04-29 (already done)
[119/304] SKIP 2025-04-30 (already done)
[120/304] SKIP 2025-05-01 (already done)
[121/304] SKIP 2025-05-02 (already done)
[122/304] SKIP 2025-05-03 (already done)
[123/304] SKIP 2025-05-04 (already done)
[124/304] SKIP 2025-05-05 (already done)
[125/304] SKIP 2025-05-06 (already done)
[126/304] SKIP 2025-05-07 (already done)
[127/304] SKIP 2025-05-08 (already done)
[128/304] SKIP 2025-05-09 (already done)
[129/304] SKIP 2025-05-10 (already done)
[130/304] SKIP 2025-05-11 (already done)
[131/304] SKIP 2025-05-12 (already done)
[132/304] SKIP 2025-05-13 (already done)
[133/304] SKIP 2025-05-14 (already done)
[134/304] SKIP 2025-05-15 (already done)
[135/304] SKIP 2025-05-16 (already done)
[136/304] SKIP 2025-05-17 (already done)
[137/304] SKIP 2025-05-18 (already done)
[138/304] SKIP 2025-05-19 (already done)
[139/304] SKIP 2025-05-20 (already done)
[140/304] SKIP 2025-05-21 (already done)
[141/304] SKIP 2025-05-22 (already done)
[142/304] SKIP 2025-05-23 (already done)
[143/304] SKIP 2025-05-24 (already done)
[144/304] SKIP 2025-05-25 (already done)
[145/304] SKIP 2025-05-26 (already done)
[146/304] SKIP 2025-05-27 (already done)
[147/304] SKIP 2025-05-28 (already done)
[148/304] SKIP 2025-05-29 (already done)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[149/304] 2025-05-30 → 76,143 trips (20.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[150/304] 2025-05-31 → 66,576 trips (22.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[151/304] 2025-06-01 → 61,217 trips (22.2s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[152/304] 2025-06-02 → 73,300 trips (20.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[153/304] 2025-06-03 → 75,314 trips (23.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[154/304] 2025-06-04 → 75,868 trips (21.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[155/304] 2025-06-05 → 75,711 trips (21.0s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[156/304] 2025-06-06 → 66,310 trips (12.1s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[157/304] 2025-06-07 → 48,902 trips (7.1s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[158/304] 2025-06-08 → 44,924 trips (7.3s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[159/304] 2025-06-09 → 55,951 trips (7.2s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[160/304] 2025-06-10 → 57,809 trips (10.1s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[161/304] 2025-06-11 → 57,473 trips (8.1s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[162/304] 2025-06-12 → 57,100 trips (7.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[163/304] 2025-06-13 → 57,109 trips (7.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[164/304] 2025-06-14 → 48,448 trips (9.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[165/304] 2025-06-15 → 44,228 trips (7.3s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[166/304] 2025-06-16 → 55,269 trips (7.3s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[167/304] 2025-06-17 → 56,612 trips (7.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[168/304] 2025-06-18 → 56,990 trips (-140.0s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[169/304] 2025-06-19 → 57,317 trips (7.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[170/304] 2025-06-20 → 56,790 trips (158.1s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[171/304] 2025-06-21 → 48,225 trips (7.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[172/304] 2025-06-22 → 44,376 trips (7.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[173/304] 2025-06-23 → 55,148 trips (7.3s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[174/304] 2025-06-24 → 55,462 trips (7.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[175/304] 2025-06-25 → 55,178 trips (7.3s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[176/304] 2025-06-26 → 54,933 trips (9.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[177/304] 2025-06-27 → 54,364 trips (7.3s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[178/304] 2025-06-28 → 45,031 trips (6.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[179/304] 2025-06-29 → 40,689 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[180/304] 2025-06-30 → 51,535 trips (9.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[181/304] 2025-07-01 → 52,262 trips (6.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[182/304] 2025-07-02 → 50,821 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[183/304] 2025-07-03 → 48,957 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[184/304] 2025-07-04 → 33,850 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[185/304] 2025-07-05 → 35,347 trips (9.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[186/304] 2025-07-06 → 34,915 trips (6.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[187/304] 2025-07-07 → 47,218 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[188/304] 2025-07-08 → 48,398 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[189/304] 2025-07-09 → 47,404 trips (9.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[190/304] 2025-07-10 → 47,223 trips (7.2s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[191/304] 2025-07-11 → 45,988 trips (7.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[192/304] 2025-07-12 → 37,553 trips (7.0s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[193/304] 2025-07-13 → 33,554 trips (7.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[194/304] 2025-07-14 → 44,512 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[195/304] 2025-07-15 → 45,439 trips (6.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[196/304] 2025-07-16 → 46,131 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[197/304] 2025-07-17 → 46,409 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[198/304] 2025-07-18 → 45,109 trips (9.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[199/304] 2025-07-19 → 36,041 trips (6.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[200/304] 2025-07-20 → 32,686 trips (6.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[201/304] 2025-07-21 → 43,462 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[202/304] 2025-07-22 → 44,974 trips (9.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[203/304] 2025-07-23 → 44,427 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[204/304] 2025-07-24 → 44,742 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[205/304] 2025-07-25 → 44,145 trips (7.0s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[206/304] 2025-07-26 → 34,698 trips (6.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[207/304] 2025-07-27 → 31,551 trips (9.3s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[208/304] 2025-07-28 → 41,784 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[209/304] 2025-07-29 → 43,553 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[210/304] 2025-07-30 → 43,715 trips (6.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[211/304] 2025-07-31 → 44,260 trips (9.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[212/304] 2025-08-01 → 43,366 trips (7.0s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[213/304] 2025-08-02 → 34,463 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[214/304] 2025-08-03 → 30,844 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[215/304] 2025-08-04 → 41,417 trips (6.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[216/304] 2025-08-05 → 43,347 trips (9.2s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[217/304] 2025-08-06 → 43,233 trips (6.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[218/304] 2025-08-07 → 43,406 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[219/304] 2025-08-08 → 43,420 trips (7.1s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[220/304] 2025-08-09 → 35,074 trips (9.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[221/304] 2025-08-10 → 31,275 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[222/304] 2025-08-11 → 41,772 trips (7.1s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[223/304] 2025-08-12 → 43,201 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[224/304] 2025-08-13 → 43,494 trips (7.3s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[225/304] 2025-08-14 → 43,654 trips (9.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[226/304] 2025-08-15 → 43,583 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[227/304] 2025-08-16 → 33,852 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[228/304] 2025-08-17 → 30,821 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[229/304] 2025-08-18 → 42,147 trips (10.0s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[230/304] 2025-08-19 → 43,216 trips (6.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[231/304] 2025-08-20 → 44,000 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[232/304] 2025-08-21 → 44,189 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[233/304] 2025-08-22 → 43,554 trips (9.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[234/304] 2025-08-23 → 34,730 trips (7.3s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[235/304] 2025-08-24 → 30,836 trips (6.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[236/304] 2025-08-25 → 42,102 trips (7.3s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[237/304] 2025-08-26 → 44,015 trips (7.1s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[238/304] 2025-08-27 → 44,190 trips (7.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[239/304] 2025-08-28 → 43,738 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[240/304] 2025-08-29 → 43,412 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[241/304] 2025-08-30 → 32,216 trips (6.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[242/304] 2025-08-31 → 28,486 trips (8.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[243/304] 2025-09-01 → 29,383 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[244/304] 2025-09-02 → 42,799 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[245/304] 2025-09-03 → 43,796 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[246/304] 2025-09-04 → 43,608 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[247/304] 2025-09-05 → 44,451 trips (9.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[248/304] 2025-09-06 → 34,662 trips (6.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[249/304] 2025-09-07 → 29,834 trips (6.2s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[250/304] 2025-09-08 → 41,498 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[251/304] 2025-09-09 → 43,039 trips (9.2s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[252/304] 2025-09-10 → 43,176 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[253/304] 2025-09-11 → 43,678 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[254/304] 2025-09-12 → 43,433 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[255/304] 2025-09-13 → 34,380 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[256/304] 2025-09-14 → 29,989 trips (9.1s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[257/304] 2025-09-15 → 41,464 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[258/304] 2025-09-16 → 42,980 trips (6.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[259/304] 2025-09-17 → 43,492 trips (7.0s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[260/304] 2025-09-18 → 43,891 trips (9.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[261/304] 2025-09-19 → 43,622 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[262/304] 2025-09-20 → 34,833 trips (6.2s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[263/304] 2025-09-21 → 30,080 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[264/304] 2025-09-22 → 41,376 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[265/304] 2025-09-23 → 42,710 trips (9.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[266/304] 2025-09-24 → 43,099 trips (7.1s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[267/304] 2025-09-25 → 44,283 trips (6.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[268/304] 2025-09-26 → 44,109 trips (6.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[269/304] 2025-09-27 → 34,605 trips (9.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[270/304] 2025-09-28 → 30,384 trips (6.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[271/304] 2025-09-29 → 41,205 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[272/304] 2025-09-30 → 43,837 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[273/304] 2025-10-01 → 44,231 trips (6.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[274/304] 2025-10-02 → 43,243 trips (9.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[275/304] 2025-10-03 → 43,874 trips (7.0s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[276/304] 2025-10-04 → 34,965 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[277/304] 2025-10-05 → 30,260 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[278/304] 2025-10-06 → 41,536 trips (10.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[279/304] 2025-10-07 → 42,482 trips (8.0s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[280/304] 2025-10-08 → 42,993 trips (7.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[281/304] 2025-10-09 → 44,124 trips (7.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[282/304] 2025-10-10 → 43,529 trips (8.1s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[283/304] 2025-10-11 → 34,410 trips (6.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[284/304] 2025-10-12 → 30,306 trips (6.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[285/304] 2025-10-13 → 39,538 trips (6.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[286/304] 2025-10-14 → 42,641 trips (10.3s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[287/304] 2025-10-15 → 40,155 trips (6.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[288/304] 2025-10-16 → 26,774 trips (5.3s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[289/304] 2025-10-17 → 33,904 trips (5.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[290/304] 2025-10-18 → 112,368 trips (57.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[291/304] 2025-10-19 → 133,404 trips (67.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[292/304] 2025-10-20 → 189,160 trips (69.7s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[293/304] 2025-10-21 → 196,314 trips (68.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[294/304] 2025-10-22 → 199,651 trips (60.6s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[295/304] 2025-10-23 → 201,566 trips (62.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[296/304] 2025-10-24 → 199,433 trips (69.1s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[297/304] 2025-10-25 → 159,141 trips (69.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[298/304] 2025-10-26 → 138,719 trips (70.9s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[299/304] 2025-10-27 → 188,408 trips (70.5s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[300/304] 2025-10-28 → 196,852 trips (71.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[301/304] 2025-10-29 → 200,163 trips (66.1s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[302/304] 2025-10-30 → 200,504 trips (64.4s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[303/304] 2025-10-31 → 198,881 trips (63.8s)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[304/304] 2025-11-01 → 155,058 trips (58.3s)

Done. 156 days processed, 148 skipped.
Total trips written: 8,904,766
Total runtime: 35.8 min

In [5]:
## Register trips table in DuckDB from all parquet files

con.execute("DROP TABLE IF EXISTS trips")
con.execute(f"""
    CREATE TABLE trips AS
    SELECT * FROM read_parquet('{STAGE_DIR}/**/*.parquet')
""")

con.execute("""
    SELECT
        COUNT(*)                       AS n_trips,
        COUNT(DISTINCT vehicle_id)     AS vehicles,
        SUM(n_handovers)               AS total_handovers,
        ROUND(AVG(duration_minutes),1) AS avg_duration_min,
        MIN(event_date)                AS first_date,
        MAX(event_date)                AS last_date
    FROM trips
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

    n_trips  vehicles  total_handovers  avg_duration_min first_date  last_date
0  13024324     96880       70977888.0              38.2 2025-01-01 2025-11-01

In [6]:
## Sanity checks

print("=== Top 10 most-active vehicles ===")
con.execute("""
    SELECT vehicle_id,
           COUNT(*)         AS n_trips,
           SUM(n_handovers) AS total_handovers
    FROM trips
    GROUP BY vehicle_id
    ORDER BY total_handovers DESC
    LIMIT 10
""").df()

=== Top 10 most-active vehicles ===

                         vehicle_id  n_trips  total_handovers
0  328657F374AEA61ABE5277C7CED9824E     3820          24481.0
1  79335A7796FD7F70CE3A2A208D9002EC     1568          23181.0
2  C76EE09311EDCCA55A4A9E89F176BD45     3485          21805.0
3  0349865D2EADAC239038E9D9136708D8     3363          21117.0
4  B7F65B2DE6F7BF91D7F9C3D5D2F38868     3412          20940.0
5  EB8CDD68A5F52E62C17816178BC53096     3088          19970.0
6  B151A689C48684D8B7F1BFB2CDB322C9     1512          19571.0
7  225DC783A88D79F028CF21FE5D1F5213     3048          19341.0
8  A878BCE63F7A8E33A9C634E17D80761C     2943          19175.0
9  B7F65B2DE6F7BF9117FE34FC6D1A5B8C     1958          19098.0

In [7]:
## Inspect most active vehicle

top_vehicle = con.execute("""
    SELECT vehicle_id FROM trips
    GROUP BY vehicle_id
    ORDER BY SUM(n_handovers) DESC
    LIMIT 1
""").fetchone()[0]

print(f"Vehicle: {top_vehicle}")
con.execute(f"""
    SELECT trip_id, trip_start, trip_end, duration_minutes,
           n_handovers, n_cells, cell_sequence
    FROM trips
    WHERE vehicle_id = '{top_vehicle}'
    ORDER BY trip_start
    LIMIT 20
""").df()

Vehicle: 328657F374AEA61ABE5277C7CED9824E

,trip_id,trip_start,trip_end,duration_minutes,n_handovers,n_cells,cell_sequence
0,328657F374AEA61ABE5277C7CED9824E_trip_002,2025-03-04 21:15:23.788,2025-03-04 21:47:42.986,32.3,5.0,5,105504441 -> 105504273 -> 105504266 -> 1055044...
1,328657F374AEA61ABE5277C7CED9824E_trip_004,2025-03-04 22:19:59.650,2025-03-04 22:36:08.641,16.2,3.0,3,105504266 -> 105504441 -> 105504435
2,328657F374AEA61ABE5277C7CED9824E_trip_005,2025-03-04 22:52:16.397,2025-03-04 23:08:26.519,16.2,3.0,3,105504280 -> 105504435 -> 105504266
3,328657F374AEA61ABE5277C7CED9824E_trip_006,2025-03-04 23:24:34.196,2025-03-04 23:48:47.015,24.2,4.0,3,105504280 -> 105504435 -> 105504266 -> 105504435
4,328657F374AEA61ABE5277C7CED9824E_trip_007,2025-03-05 02:38:16.582,2025-03-05 03:02:29.409,24.2,4.0,3,105504266 -> 105504435 -> 105504441 -> 105504266
5,328657F374AEA61ABE5277C7CED9824E_trip_009,2025-03-05 04:23:14.190,2025-03-05 04:55:30.826,32.3,5.0,5,105504441 -> 105504280 -> 105504435 -> 1055042...
6,328657F374AEA61ABE5277C7CED9824E_trip_011,2025-03-05 05:52:01.531,2025-03-05 06:40:25.831,48.4,7.0,5,105504435 -> 105504266 -> 105504273 -> 1055042...
7,328657F374AEA61ABE5277C7CED9824E_trip_012,2025-03-05 06:56:34.788,2025-03-05 07:44:59.262,48.4,7.0,5,105504266 -> 105504273 -> 105504280 -> 1055042...
8,328657F374AEA61ABE5277C7CED9824E_trip_013,2025-03-05 08:01:09.543,2025-03-05 08:17:19.587,16.2,3.0,3,105504280 -> 105504435 -> 105504273
9,328657F374AEA61ABE5277C7CED9824E_trip_015,2025-03-05 09:05:42.654,2025-03-05 09:21:50.351,16.1,3.0,3,105504266 -> 105504280 -> 105504435
10,328657F374AEA61ABE5277C7CED9824E_trip_016,2025-03-05 09:37:59.322,2025-03-05 10:18:21.046,40.4,6.0,4,105504280 -> 105504435 -> 105504441 -> 1055042...
11,328657F374AEA61ABE5277C7CED9824E_trip_017,2025-03-05 10:42:33.840,2025-03-05 13:07:50.629,145.3,19.0,5,105504441 -> 105504280 -> 105504435 -> 1055044...
12,328657F374AEA61ABE5277C7CED9824E_trip_018,2025-03-05 13:23:58.348,2025-03-05 13:40:06.038,16.1,3.0,3,105504280 -> 105504435 -> 105504266
13,328657F374AEA61ABE5277C7CED9824E_trip_019,2025-03-05 13:56:15.002,2025-03-05 14:20:27.808,24.2,4.0,3,105504280 -> 105504266 -> 105504435 -> 105504266
14,328657F374AEA61ABE5277C7CED9824E_trip_020,2025-03-05 14:36:35.448,2025-03-05 16:13:24.205,96.8,13.0,5,105504441 -> 105504266 -> 105504441 -> 1055044...
15,328657F374AEA61ABE5277C7CED9824E_trip_021,2025-03-05 16:29:33.026,2025-03-05 17:26:03.763,56.5,8.0,4,105504441 -> 105504266 -> 105504435 -> 1055044...
16,328657F374AEA61ABE5277C7CED9824E_trip_023,2025-03-05 17:58:20.450,2025-03-05 18:30:37.069,32.3,5.0,4,105504266 -> 105504435 -> 105504280 -> 1055042...
17,328657F374AEA61ABE5277C7CED9824E_trip_024,2025-03-05 18:45:17.730,2025-03-05 19:01:26.702,16.2,3.0,3,105504266 -> 105504441 -> 105504280
18,328657F374AEA61ABE5277C7CED9824E_trip_028,2025-03-05 20:06:01.224,2025-03-05 20:30:14.047,24.2,4.0,3,105504280 -> 105504266 -> 105504435 -> 105504266
19,328657F374AEA61ABE5277C7CED9824E_trip_030,2025-03-05 21:10:37.049,2025-03-05 21:26:44.788,16.1,3.0,3,105504441 -> 105504266 -> 105504435

In [8]:
con.execute(f"""
    SELECT trip_id, trip_start, trip_end, duration_minutes,
           n_handovers, n_cells, cell_sequence
    FROM trips
    WHERE vehicle_id = 'A2FCC9AF8E480E683F655628A3E5E38D'
    ORDER BY trip_start
    LIMIT 20
""").df()

,trip_id,trip_start,trip_end,duration_minutes,n_handovers,n_cells,cell_sequence
0,A2FCC9AF8E480E683F655628A3E5E38D_trip_007,2025-05-15 21:29:19.993,2025-05-15 22:01:31.265,32.2,5.0,5,182035976 -> 182043146 -> 182074122 -> 1820485...
1,A2FCC9AF8E480E683F655628A3E5E38D_trip_008,2025-05-15 22:17:36.970,2025-05-15 22:33:42.468,16.1,3.0,3,182074136 -> 182311177 -> 182043158
2,A2FCC9AF8E480E683F655628A3E5E38D_trip_002,2025-05-16 00:42:40.725,2025-05-16 02:09:57.997,87.3,12.0,9,182043144 -> 182043158 -> 182035976 -> 1820175...
3,A2FCC9AF8E480E683F655628A3E5E38D_trip_039,2025-05-17 20:44:33.790,2025-05-17 21:40:55.089,56.4,8.0,4,183462719 -> 181786391 -> 182309910 -> 1823098...
4,A2FCC9AF8E480E683F655628A3E5E38D_trip_042,2025-05-17 22:53:29.677,2025-05-17 23:17:37.679,24.1,4.0,4,182309896 -> 181786390 -> 182043144 -> 182035991
5,A2FCC9AF8E480E683F655628A3E5E38D_trip_027,2025-05-19 11:26:01.247,2025-05-19 12:14:17.806,48.3,7.0,5,182035990 -> 182043158 -> 182311190 -> 1820551...
6,A2FCC9AF8E480E683F655628A3E5E38D_trip_030,2025-05-19 13:42:54.768,2025-05-19 13:59:00.379,16.1,3.0,3,182058506 -> 182074121 -> 182074135
7,A2FCC9AF8E480E683F655628A3E5E38D_trip_039,2025-05-19 18:32:40.767,2025-05-19 19:12:54.334,40.2,6.0,4,182074121 -> 182074129 -> 182074135 -> 1820741...
8,A2FCC9AF8E480E683F655628A3E5E38D_trip_040,2025-05-19 19:29:08.727,2025-05-19 19:45:23.166,16.3,3.0,3,182311690 -> 182061078 -> 182061064
9,A2FCC9AF8E480E683F655628A3E5E38D_trip_041,2025-05-19 20:01:28.827,2025-05-19 20:49:45.407,48.3,7.0,6,182061080 -> 182061066 -> 182061065 -> 1820431...
10,A2FCC9AF8E480E683F655628A3E5E38D_trip_042,2025-05-19 21:05:51.198,2025-05-19 21:46:17.748,40.4,6.0,6,182017545 -> 182322185 -> 182187017 -> 1823116...
11,A2FCC9AF8E480E683F655628A3E5E38D_trip_043,2025-05-19 22:10:25.987,2025-05-19 22:26:31.604,16.1,3.0,3,181821448 -> 182074121 -> 182061064
12,A2FCC9AF8E480E683F655628A3E5E38D_trip_044,2025-05-19 22:58:42.908,2025-05-19 23:53:10.999,54.5,8.0,7,182061078 -> 182061064 -> 182061078 -> 1823116...
13,A2FCC9AF8E480E683F655628A3E5E38D_trip_024,2025-05-20 06:47:55.970,2025-05-20 07:05:06.441,17.2,3.0,3,9852418 -> 182035984 -> 182061079 -> 9852418 -...
14,A2FCC9AF8E480E683F655628A3E5E38D_trip_047,2025-05-20 15:00:47.371,2025-05-20 15:57:20.526,56.6,8.0,7,9852418 -> 182061065 -> 181839639 -> 182035976...
15,A2FCC9AF8E480E683F655628A3E5E38D_trip_048,2025-05-20 19:18:53.081,2025-05-20 19:35:07.189,16.2,3.0,3,182311689 -> 182187031 -> 182035976
16,A2FCC9AF8E480E683F655628A3E5E38D_trip_049,2025-05-20 19:51:12.692,2025-05-20 20:07:18.206,16.1,3.0,3,182035991 -> 183462499 -> 182061065
17,A2FCC9AF8E480E683F655628A3E5E38D_trip_053,2025-05-20 21:31:28.466,2025-05-20 21:47:36.505,16.1,3.0,3,182061079 -> 182035990 -> 182043144
18,A2FCC9AF8E480E683F655628A3E5E38D_trip_001,2025-05-21 00:04:34.166,2025-05-21 00:59:40.867,55.1,3.0,3,182035976 -> 243207038 -> 182035984 -> 1820359...
19,A2FCC9AF8E480E683F655628A3E5E38D_trip_021,2025-05-21 14:44:10.889,2025-05-21 15:08:17.987,24.1,4.0,4,9852418 -> 243207038 -> 182035990 -> 182187017...

In [9]:
# Export trips sample to Excel
result = con.execute("""
    SELECT trip_id, trip_start, trip_end, duration_minutes,
           n_handovers, n_cells, cell_sequence
    FROM trips
    WHERE vehicle_id = 'A2FCC9AF8E480E683F655628A3E5E38D'
    ORDER BY trip_start
""").df()

result.to_excel('/home/jovyan/data/stage/trips/A2FCC9AF8E480E683F655628A3E5E38D_all_trips.xlsx', index=False)
print(f"Exported {len(result)} rows")

Exported 532 rows

In [10]:
con.execute("""
    SELECT MIN(event_date), MAX(event_date), COUNT(DISTINCT event_date)
    FROM trips
""").df()

  min(event_date) max(event_date)  count(DISTINCT event_date)
0      2025-01-01      2025-11-01                         299